//! 1:1 port of Go `regexp_test.go` (`TestAnnotationRegexp`): every annotation /
//! repository regexp used in DevStats configuration must match (or not match) the
//! same strings under the Go→Rust regexp adapter as under Go's `regexp`.

use devstatscode::goregex;

/// (regexp, string, expected match) — same rows and order as the Go table.
const TEST_CASES: &[(&str, &str, bool)] = &[
    (r"^v\d+\.\d+\.0(-(alpha|beta|rc)\.\d+)?$", "v1.0.0", true),
    (
        r"^v\d+\.\d+\.0(-(alpha|beta|rc)\.\d+)?$",
        "v1.0.0-rc.1",
        true,
    ),
    (
        r"^v\d+\.\d+\.0(-(alpha|beta|rc)\.\d+)?$",
        "v1.0.0-beta.1.dev.20221204",
        false,
    ),
    (
        r"^v\d+\.\d+\.0(-(alpha|beta|rc)\.\d+)?$",
        "v1.0.0-alpha.4",
        true,
    ),
    (
        r"^v\d+\.\d+\.0(-(alpha|beta|rc)\.\d+)?$",
        "v1.0.0-beta.4",
        true,
    ),
    (
        r"^v\d+\.\d+\.0(-(alpha|beta|rc)\.\d+)?$",
        "v1.0.1-rc.1",
        false,
    ),
    (r"^v\d+\.\d+\.0(-(alpha|beta|rc)\.\d+)?$", "v1.0.2", false),
    (
        r"^v\d+\.\d+\.0(-(alpha|beta|rc)\.\d+)?$",
        "v1.0.3-rc.1",
        false,
    ),
    (
        r"^(v\d+\.\d+\.\d+|release-\d{4}-\d{2}-\d{2})$",
        "v1.2.3",
        true,
    ),
    (
        r"^(v\d+\.\d+\.\d+|release-\d{4}-\d{2}-\d{2})$",
        "v1.2",
        false,
    ),
    (
        r"^(v\d+\.\d+\.\d+|release-\d{4}-\d{2}-\d{2})$",
        "v1.2.3.4",
        false,
    ),
    (
        r"^(v\d+\.\d+\.\d+|release-\d{4}-\d{2}-\d{2})$",
        "release-2021-05-15",
        true,
    ),
    (
        r"^(v\d+\.\d+\.\d+|release-\d{4}-\d{2}-\d{2})$",
        "release-201-05-15",
        false,
    ),
    (r"^v((0\.\d+)|(\d+\.\d+\.0))$", "v0.0", true),
    (r"^v((0\.\d+)|(\d+\.\d+\.0))$", "v1.0", false),
    (r"^v((0\.\d+)|(\d+\.\d+\.0))$", "0.0", false),
    (r"^v((0\.\d+)|(\d+\.\d+\.0))$", " v0.0 ", false),
    (r"^v((0\.\d+)|(\d+\.\d+\.0))$", "", false),
    (r"^v((0\.\d+)|(\d+\.\d+\.0))$", "v1.0.0", true),
    (r"^v((0\.\d+)|(\d+\.\d+\.0))$", "v1.15.0", true),
    (r"^v((0\.\d+)|(\d+\.\d+\.0))$", "v0.0.0", true),
    (r"^v((0\.\d+)|(\d+\.\d+\.0))$", "v1.2.3", false),
    (r"^v((0\.\d+)|(\d+\.\d+\.0))$", "V1.4.9", false),
    (r"^v?\d+\.\d+\.0$", "v0.0.0", true),
    (r"^v?\d+\.\d+\.0$", "v1.0.0", true),
    (r"^v?\d+\.\d+\.0$", "0.12.0", true),
    (r"^v(\d+\.){1,2}\d+$", "v1.1", true),
    (r"^v(\d+\.){1,2}\d+$", "v2.3.4", true),
    (r"^v(\d+\.){1,2}\d+$", "v1.2.3.4", false),
    (
        r"^(release-\d+\.\d+\.\d+|\d+\.\d+\.0)$",
        "release-0.1.2",
        true,
    ),
    (r"^(release-\d+\.\d+\.\d+|\d+\.\d+\.0)$", "1.2.0", true),
    (
        r"^(release-\d+\.\d+\.\d+|\d+\.\d+\.0)$",
        "release-0.1",
        false,
    ),
    (r"^(release-\d+\.\d+\.\d+|\d+\.\d+\.0)$", "2.3.4", false),
    (r"^jenkins-\d+\.\d+$", "2.3.4", false),
    (r"^jenkins-\d+\.\d+$", "jenkins-2", false),
    (r"^jenkins-\d+\.\d+$", "jenkins-2.1", true),
    (r"^jenkins-\d+\.\d+$", "jenkins-2.1.1", false),
    (r"^v(\d+\.\d+\.\d+|\d\d\d)$", "1.2.3", false),
    (r"^v(\d+\.\d+\.\d+|\d\d\d)$", "v0.1.2", true),
    (r"^v(\d+\.\d+\.\d+|\d\d\d)$", "v000", true),
    (r"^v(\d+\.\d+\.\d+|\d\d\d)$", "007", false),
    (r"^v(\d+\.\d+\.\d+|\d\d\d)$", "v007", true),
    (r"^v(\d+\.\d+\.\d+|\d\d\d)$", "v0000", false),
    (r"^v(\d+\.\d+\.\d+|\d\d\d)$", "05", false),
    (r"^v(\d+\.\d+\.\d+|\d\d\d)$", "v0.2", false),
    (r"^v?\d+\.\d+\.\d+(-[\w-+\d.]+)?$", "1.2.3", true),
    (r"^v?\d+\.\d+\.\d+(-[\w-+\d.]+)?$", "v1.12.23", true),
    (r"^v?\d+\.\d+\.\d+(-[\w-+\d.]+)?$", "v1.0.1-", false),
    (r"^v?\d+\.\d+\.\d+(-[\w-+\d.]+)?$", "v1.0.1-a", true),
    (r"^v?\d+\.\d+\.\d+(-[\w-+\d.]+)?$", "v1.0.1-.", true),
    (r"^v?\d+\.\d+\.\d+(-[\w-+\d.]+)?$", "v1.0.1--", true),
    (r"^v?\d+\.\d+\.\d+(-[\w-+\d.]+)?$", "v1.0.1-+", true),
    (r"^v?\d+\.\d+\.\d+(-[\w-+\d.]+)?$", "v1.0.1-0", true),
    (r"^v?\d+\.\d+\.\d+(-[\w-+\d.]+)?$", "1.0.1-rc.1", true),
    (r"^v?\d+\.\d+\.\d+(-[\w-+\d.]+)?$", "v1.0.1-alpha", true),
    (r"^v?\d+\.\d+\.\d+(-[\w-+\d.]+)?$", "1.0.1-beta2", true),
    (r"^v?\d+\.\d+\.\d+(-[\w-+\d.]+)?$", "v1.0.1-rc.3", true),
    (r"^v?\d+\.\d+\.\d+(-[\w-+\d.]+)?$", "v1.0.1-al b", false),
    (r"^v\d+\.\d+\.(0|\d*[05]0)$", "v1.0.0", true),
    (r"^v\d+\.\d+\.(0|\d*[05]0)$", "v1.0.10", false),
    (r"^v\d+\.\d+\.(0|\d*[05]0)$", "v1.0.05", false),
    (r"^v\d+\.\d+\.(0|\d*[05]0)$", "v1.0.5", false),
    (r"^v\d+\.\d+\.(0|\d*[05]0)$", "v1.0.50", true),
    (r"^v\d+\.\d+\.(0|\d*[05]0)$", "v1.0.49", false),
    (r"^v\d+\.\d+\.(0|\d*[05]0)$", "v1.0.51", false),
    (r"^v\d+\.\d+\.(0|\d*[05]0)$", "v1.0.55", false),
    (r"^v\d+\.\d+\.(0|\d*[05]0)$", "v1.0.11", false),
    (r"^v\d+\.\d+\.(0|\d*[05]0)$", "v1.0.100", true),
    (r"^v\d+\.\d+\.(0|\d*[05]0)$", "v1.3.150", true),
    (r"^v\d+\.\d+\.(0|\d*[05]0)$", "v3.0.200", true),
    (r"^v\d+\.\d+\.(0|\d*[05]0)$", "v0.5.500", true),
    (r"^v\d+\.\d+\.(0|\d*[05]0)$", "v10.10.550", true),
    (r"^v\d+\.\d+\.(0|\d*[05]0)$", "v10.10.520", false),
    (r"^v\d+\.\d+\.(0|\d+0)$", "v10.10.0", true),
    (r"^v\d+\.\d+\.(0|\d+0)$", "v10.11.10", true),
    (r"^v\d+\.\d+\.(0|\d+0)$", "v10.12.100", true),
    (r"^v\d+\.\d+\.(0|\d+0)$", "v10.13.101", false),
    (r"^v\d+\.\d+\.(0|\d+0)$", "v10.14.11", false),
    (r"^v\d+\.\d+\.(0|\d+0)$", "v10.15.1", false),
    (r"^v\d+\.\d+\.(0|\d+0)$", "v10.15", false),
    (r"^v\d+\.\d+\.\d*[05]$", "v10.15", false),
    (r"^v\d+\.\d+\.\d*[05]$", "v10.15.0", true),
    (r"^v\d+\.\d+\.\d*[05]$", "v10.15.10", true),
    (r"^v\d+\.\d+\.\d*[05]$", "v10.15.205", true),
    (r"^v\d+\.\d+\.\d*[05]$", "v10.15.201", false),
    (r"^v\d+\.\d+\.\d*[05]$", "v10.15.204", false),
    (r"^v\d+\.\d+\.\d*[05]$", "v10.15.04", false),
    (r"^v\d+\.\d+\.\d*[05]$", "v10.15.24", false),
    (r"^v\d+\.\d+\.\d*[05]$", "v10.15.4", false),
    (r"^v\d+\.\d+\.\d*[05]$", "v10.15.200", true),
    (r"^v\d+\.\d+\.\d*[05]$", "v10.15.15", true),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "vendor/", true),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "_vendor/", true),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "/vendor/", true),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "abc/vendor/a", true),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "vendor//", true),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "_vendor/abc/", true),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "/vendor/ abc", true),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "vendor", false),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "vendor_a", false),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "/vendor", false),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "abc/vendor", false),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "/vendor_a", false),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "abc/vendor_a", false),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "Godeps/", true),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "_Godeps/", true),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "/Godeps/", true),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "abc/Godeps/a", true),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "Godeps//", true),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "_Godeps/abc/", true),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "/Godeps/ abc", true),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "Godeps", false),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "Godeps_a", false),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "/Godeps", false),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "abc/Godeps", false),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "/Godeps_a", false),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "abc/Godeps_a", false),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "workspace/", false),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "_workspace/", true),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "__workspace/", true),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "/workspace/", false),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "/_workspace/", true),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "/__workspace/", true),
    (
        r"(^|/)_?(vendor|Godeps|_workspace)/",
        "abc/workspace/a",
        false,
    ),
    (
        r"(^|/)_?(vendor|Godeps|_workspace)/",
        "abc/_workspace/a",
        true,
    ),
    (
        r"(^|/)_?(vendor|Godeps|_workspace)/",
        "abc/__workspace/a",
        true,
    ),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "workspace//", false),
    (
        r"(^|/)_?(vendor|Godeps|_workspace)/",
        "_workspace/abc/",
        true,
    ),
    (
        r"(^|/)_?(vendor|Godeps|_workspace)/",
        "__workspace/abc/",
        true,
    ),
    (
        r"(^|/)_?(vendor|Godeps|_workspace)/",
        "/workspace/ abc",
        false,
    ),
    (
        r"(^|/)_?(vendor|Godeps|_workspace)/",
        "/_workspace/ abc",
        true,
    ),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "workspace", false),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "_workspace", false),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "workspace_a", false),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "_workspace_a", false),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "/workspace", false),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "/_workspace", false),
    (
        r"(^|/)_?(vendor|Godeps|_workspace)/",
        "abc/workspace",
        false,
    ),
    (
        r"(^|/)_?(vendor|Godeps|_workspace)/",
        "abc/_workspace",
        false,
    ),
    (r"(^|/)_?(vendor|Godeps|_workspace)/", "/workspace_a", false),
    (
        r"(^|/)_?(vendor|Godeps|_workspace)/",
        "/_workspace_a",
        false,
    ),
    (
        r"(^|/)_?(vendor|Godeps|_workspace)/",
        "abc/workspace_a",
        false,
    ),
    (
        r"(^|/)_?(vendor|Godeps|_workspace)/",
        "abc/_workspace_a",
        false,
    ),
    (
        r"(?i)^(plexistor|stack\s*point\s*cloud|greenqloud|netapp)(,?\s*inc\.?)?$",
        "GreenQLoud, Inc.",
        true,
    ),
    (r"^\d+\.(0|\d+0)$", "0.0", true),
    (r"^\d+\.(0|\d+0)$", "0.10", true),
    (r"^\d+\.(0|\d+0)$", "1.220", true),
    (r"^\d+\.(0|\d+0)$", "2.00", true),
    (r"^\d+\.(0|\d+0)$", "2.11", false),
    (r"^\d+\.(0|\d+0)$", "0.73", false),
    (r"^\d+\.(0|\d+0)$", "0.a0", false),
    (r"^\d+\.(0|\d+0)$", "2.10.0", false),
    (r"^v\d+\.\d+\.\d*0(\+k3s\.?1)?$", "v0.0.0", true),
    (r"^v\d+\.\d+\.\d*0(\+k3s\.?1)?$", "v0.0.1", false),
    (r"^v\d+\.\d+\.\d*0(\+k3s\.?1)?$", "v0.0.10", true),
    (r"^v\d+\.\d+\.\d*0(\+k3s\.?1)?$", "v0.0.12", false),
    (r"^v\d+\.\d+\.\d*0(\+k3s\.?1)?$", "v1.16.10+k3s1", true),
    (r"^v\d+\.\d+\.\d*0(\+k3s\.?1)?$", "v1.16.10-k3s1", false),
    (r"^v\d+\.\d+\.\d*0(\+k3s\.?1)?$", "v1.16.11+k3s1", false),
    (r"^v\d+\.\d+\.\d*0(\+k3s\.?1)?$", "v1.12.0+k3s.1", true),
    (r"^v\d+\.\d+\.\d*0(\+k3s\.?1)?$", "v1.12.0+k3s", false),
    (
        r"(?i)^(ibuildthecloud|rancher)\/.*k3(s|d).*$",
        "ibuildthecloud/k3s",
        true,
    ),
    (
        r"(?i)^(ibuildthecloud|rancher)\/.*k3(s|d).*$",
        "IBuildTheCloud/K3s",
        true,
    ),
    (
        r"(?i)^(ibuildthecloud|rancher)\/.*k3(s|d).*$",
        "buildthecloud/k3s",
        false,
    ),
    (
        r"(?i)^(ibuildthecloud|rancher)\/.*k3(s|d).*$",
        "iibuildthecloud/k3s",
        false,
    ),
    (
        r"(?i)^(ibuildthecloud|rancher)\/.*k3(s|d).*$",
        "iibuildtheclouds/k3s",
        false,
    ),
    (
        r"(?i)^(ibuildthecloud|rancher)\/.*k3(s|d).*$",
        "ibuildtheclouds/k3s",
        false,
    ),
    (
        r"(?i)^(ibuildthecloud|rancher)\/.*k3(s|d).*$",
        "rancher/k3s",
        true,
    ),
    (
        r"(?i)^(ibuildthecloud|rancher)\/.*k3(s|d).*$",
        "ancher/k3s",
        false,
    ),
    (
        r"(?i)^(ibuildthecloud|rancher)\/.*k3(s|d).*$",
        "xrancher/k3s",
        false,
    ),
    (
        r"(?i)^(ibuildthecloud|rancher)\/.*k3(s|d).*$",
        "rancher-lab/k3s",
        false,
    ),
    (
        r"(?i)^(ibuildthecloud|rancher)\/.*k3(s|d).*$",
        "a-rancher-org/k3s",
        false,
    ),
    (
        r"(?i)^(ibuildthecloud|rancher)\/.*k3(s|d).*$",
        "Rancher/K3s",
        true,
    ),
    (
        r"(?i)^(ibuildthecloud|rancher)\/.*k3(s|d).*$",
        "rancher/k3D",
        true,
    ),
    (
        r"(?i)^(ibuildthecloud|rancher)\/.*k3(s|d).*$",
        "Rancher/myk3s",
        true,
    ),
    (
        r"(?i)^(ibuildthecloud|rancher)\/.*k3(s|d).*$",
        "Rancher/k3docker",
        true,
    ),
    (
        r"(?i)^(ibuildthecloud|rancher)\/.*k3(s|d).*$",
        "IBuildTheCloud/new-K3S-v.2",
        true,
    ),
    (
        r"(?i)^((ibuildthecloud|rancher)\/.*k3(s|d).*|k3s-io\/.*)$",
        "Rancher/myk3s",
        true,
    ),
    (
        r"(?i)^((ibuildthecloud|rancher)\/.*k3(s|d).*|k3s-io\/.*)$",
        "k3s-io/k3s",
        true,
    ),
    (
        r"(?i)^((ibuildthecloud|rancher)\/.*k3(s|d).*|k3s-io\/.*)$",
        "k3s-io/whatever",
        true,
    ),
    (
        r"(?i)^(ibuildthecloud|rancher)\/.*k3(s|d).*$",
        "k3s-io/whatever",
        false,
    ),
    (r"^v?\d+\.\d+(\.0)?$", "v2.0", true),
    (r"^v?\d+\.\d+(\.0)?$", "v2.1", true),
    (r"^v?\d+\.\d+(\.0)?$", "1.0", true),
    (r"^v?\d+\.\d+(\.0)?$", "1.2", true),
    (r"^v?\d+\.\d+(\.0)?$", "2.3.0", true),
    (r"^v?\d+\.\d+(\.0)?$", "v2.0.0", true),
    (r"^v?\d+\.\d+(\.0)?$", "v2.15.0", true),
    (r"^v?\d+\.\d+(\.0)?$", "v2", false),
    (r"^v?\d+\.\d+(\.0)?$", "20", false),
    (r"^v?\d+\.\d+(\.0)?$", "v2.0.1", false),
    (r"^v?\d+\.\d+(\.0)?$", "2.3.5", false),
    (r"^v?\d+\.\d+(\.0)?$", "v2.0.0.0", false),
    (r"^v(\d+\.\d+\.\d+$|1)", "v3.0.0", true),
    (r"^v(\d+\.\d+\.\d+$|1)", "v2.1.0", true),
    (r"^v(\d+\.\d+\.\d+$|1)", "v2.1.0-xyz", false),
    (r"^v(\d+\.\d+\.\d+$|1)", "v2.1", false),
    (r"^v(\d+\.\d+\.\d+$|1)", "v1alpha1", true),
    (r"^v(\d+\.\d+\.\d+$|1)", "v1.0", true),
    (r"^v(\d+\.\d+\.\d+$|1)", "v1.0.0", true),
    (r"^v(\d+\.\d+\.\d+$|1)", "v1.0.0.0", true),
    (
        r"(?i)^(appdynamics(\s+(llc|\(cisco\)))?|epsagon(\s+(llc))?|banzai\s*?cloud(\s+zrt)?)$",
        "AppDynamics LLC",
        true,
    ),
    (
        r"(?i)^(appdynamics(\s+(llc|\(cisco\)))?|epsagon(\s+(llc))?|banzai\s*?cloud(\s+zrt)?)$",
        "Appdynamics   LLC",
        true,
    ),
    (
        r"(?i)^(appdynamics(\s+(llc|\(cisco\)))?|epsagon(\s+(llc))?|banzai\s*?cloud(\s+zrt)?)$",
        "appDynamics\tLLC",
        true,
    ),
    (
        r"(?i)^(appdynamics(\s+(llc|\(cisco\)))?|epsagon(\s+(llc))?|banzai\s*?cloud(\s+zrt)?)$",
        "AppDynamics (Cisco)",
        true,
    ),
    (
        r"(?i)^(appdynamics(\s+(llc|\(cisco\)))?|epsagon(\s+(llc))?|banzai\s*?cloud(\s+zrt)?)$",
        "appdynamics  (cisco)",
        true,
    ),
    (
        r"(?i)^(appdynamics(\s+(llc|\(cisco\)))?|epsagon(\s+(llc))?|banzai\s*?cloud(\s+zrt)?)$",
        "Epsagon",
        true,
    ),
    (
        r"(?i)^(appdynamics(\s+(llc|\(cisco\)))?|epsagon(\s+(llc))?|banzai\s*?cloud(\s+zrt)?)$",
        "Epsagon LLC",
        true,
    ),
    (
        r"(?i)^(appdynamics(\s+(llc|\(cisco\)))?|epsagon(\s+(llc))?|banzai\s*?cloud(\s+zrt)?)$",
        "BanzaiCloud",
        true,
    ),
    (
        r"(?i)^(appdynamics(\s+(llc|\(cisco\)))?|epsagon(\s+(llc))?|banzai\s*?cloud(\s+zrt)?)$",
        "Banzai Cloud",
        true,
    ),
    (
        r"(?i)^(appdynamics(\s+(llc|\(cisco\)))?|epsagon(\s+(llc))?|banzai\s*?cloud(\s+zrt)?)$",
        "Banzai Cloud Zrt",
        true,
    ),
    (
        r"(?i)^(appdynamics(\s+(llc|\(cisco\)))?|epsagon(\s+(llc))?|banzai\s*?cloud(\s+zrt)?)$",
        "banzai  cloud\tzrt",
        true,
    ),
    (
        r"(?i)^(appdynamics(\s+(llc|\(cisco\)))?|epsagon(\s+(llc))?|banzai\s*?cloud(\s+zrt)?)$",
        "banzaicloudzrt",
        false,
    ),
    (r"^(knative-)?v\d+\.\d+\.0$", "knative-v1.1.4", false),
    (r"^(knative-)?v\d+\.\d+\.0$", "v1.1.0", true),
    (r"^(knative-)?v\d+\.\d+\.0$", "v1.1.4", false),
    (r"^(knative-)?v\d+\.\d+\.0$", "knative-v1.1.0", true),
    (r"^v\d+\.\d*[05]\.0$", "v0.0.0", true),
    (r"^v\d+\.\d*[05]\.0$", "v0.0.1", false),
    (r"^v\d+\.\d*[05]\.0$", "v0.5.0", true),
    (r"^v\d+\.\d*[05]\.0$", "v0.10.0", true),
    (r"^v\d+\.\d*[05]\.0$", "v0.15.0", true),
    (r"^v\d+\.\d*[05]\.0$", "v0.10.1", false),
    (r"^v\d+\.\d*[05]\.0$", "v10.225.0", true),
    (r"^v\d+\.\d*[05]\.0$", "v0.5", false),
    (r"^v\d+\.\d*[05]\.0$", "0.15.0", false),
    (r"^ms-general-\d+\.\d+\.\d*0$", "ms-general-1.2.0", true),
    (r"^ms-general-\d+\.\d+\.\d*0$", "ms-general-0.2.10", true),
    (r"^ms-general-\d+\.\d+\.\d*0$", "ms-general-1.0.11", false),
    (r"^ms-general-\d+\.\d+\.\d*0$", "ms-general-2.4.1", false),
    (r"^ms-general-\d+\.\d+\.\d*0$", "ms-general-0.0.200", true),
    (r"^ms-general-\d+\.\d+\.\d*0$", " ms-general-1.1.10 ", false),
    (r"^\d+\.0\.0(\.Final)?$", "8.1.1", false),
    (r"^\d+\.0\.0(\.Final)?$", "8.1.0", false),
    (r"^\d+\.0\.0(\.Final)?$", "8.0.1", false),
    (r"^\d+\.0\.0(\.Final)?$", "8.0.0", true),
    (r"^\d+\.0\.0(\.Final)?$", "7.0.0.final", false),
    (r"^\d+\.0\.0(\.Final)?$", "7.0.0.Final", true),
    (r"^\d+\.0\.0(\.Final)?$", "7.0.0.Finally", false),
    (r"^\d+\.0\.0(\.Final)?$", "7.0.1.Final", false),
    (r"^\d+\.0\.0(\.Final)?$", "7.1.0.Final", false),
    (r"^v\d+\.\d+\.0$", "v1.2.3", false),
    (r"^v\d+\.\d+\.0$", "v1.2.0", true),
    (r"^v\d+\.\d+\.0(-beta\.\d*0)?$", "v1.2.0", true),
    (r"^v\d+\.\d+\.0(-beta\.\d*0)?$", "v1.2.1", false),
    (r"^v\d+\.\d+\.0(-beta\.\d*0)?$", "v1.0.0-beta.0", true),
    (r"^v\d+\.\d+\.0(-beta\.\d*0)?$", "v1.0.0-beta.10", true),
    (r"^v\d+\.\d+\.0(-beta\.\d*0)?$", "v1.0.0-beta.1", false),
    (r"^v\d+\.\d+\.0(-beta\.\d*0)?$", "v1.0.0-beta.101", false),
    (r"^v\d+\.\d+\.\d*0$", "v1.2.0", true),
    (r"^v\d+\.\d+\.\d*0$", "v1.2.10", true),
    (r"^v\d+\.\d+\.\d*0$", "v1.2.110", true),
    (r"^v\d+\.\d+\.\d*0$", "v1.2.1", false),
    (r"^v\d+\.\d+\.0\+k0s\.\d+$", "v1.2.0+k0s.0", true),
    (r"^v\d+\.\d+\.0\+k0s\.\d+$", "v1.2.0-beta.+k0s.0", false),
    (r"^v\d+\.\d+\.0\+k0s\.\d+$", "v1.2.0+k0s.1", true),
    (
        r"(?i)^(interlink-hq\/.*|interTwin-eu\/(.*interlink.*|vk-test-set))$",
        "interTwin-eu/interLink",
        true,
    ),
    (
        r"(?i)^(interlink-hq\/.*|interTwin-eu\/(.*interlink.*|vk-test-set))$",
        "intertwin-eu/interLink",
        true,
    ),
    (
        r"(?i)^(interlink-hq\/.*|interTwin-eu\/(.*interlink.*|vk-test-set))$",
        "interlink-hq/interLink",
        true,
    ),
    (
        r"(?i)^(interlink-hq\/.*|interTwin-eu\/(.*interlink.*|vk-test-set))$",
        "interlink-hq/x-y-z",
        true,
    ),
    (
        r"(?i)^interTwin-eu\/(.*interlink.*|vk-test-set)$",
        "interTwin-eu/interLink",
        true,
    ),
    (
        r"(?i)^interTwin-eu\/(.*interlink.*|vk-test-set)$",
        "intertwin-eu/interlink",
        true,
    ),
    (
        r"(?i)^intertwin-eu\/(.*interlink.*|vk-test-set)$",
        "interTwin-eu/interLink",
        true,
    ),
    (
        r"(?i)^interTwin-eu\/(.*interlink.*|vk-test-set)$",
        "interTwin-eu/vk-test-set",
        true,
    ),
];

#[test]
fn annotation_regexp() {
    assert_eq!(TEST_CASES.len(), 264);
    for (index, (re, s, expected)) in TEST_CASES.iter().enumerate() {
        let re = goregex::compile(re).unwrap_or_else(|e| {
            panic!(
                "test number {}: regexp `{re}` failed to compile: {e}",
                index + 1
            )
        });
        let got = re.is_match(s);
        assert_eq!(
            got, *expected,
            "test number {}, expected match result '{}' for string '{}' matching regexp '{}', got '{}'",
            index + 1, expected, s, re, got
        );
    }
}
