//! Go ⇄ Rust compatibility tests for `reconcile_dbs`.
//!
//! Every case gets its own scratch databases per side
//! (`dbtest_reconcile_<case>_<go|rs>_<tgt|src|p1|…>`, schema from
//! `compat/fixtures/structure/full_structure.sql`, deterministic seed rows
//! generated by [`seed_sql`] from a small "world" of events — see
//! `compat/fixtures/reconcile_dbs/README.md`) and runs the binary in a
//! scratch directory holding `projects.yaml` (the `shared`/`project` modes)
//! and the `util_sql/postprocess_*_ids.sql` scripts of the targeted
//! post-processing. Compared: exit code, stdout (database names, the
//! scratch directory, the `since <timestamp>` of the header and the
//! durations masked), the `Error: '…'` / `PqError:` stderr lines and every
//! table of the target database afterwards (`gha_repos` without its
//! `now()`-defaulted timestamps).
//!
//! The tests need a PostgreSQL server (`test.sh` finds one; skipped
//! otherwise). The unit tests of the binary cover the pure helpers.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use chrono::{Duration, NaiveDate, Utc};
use devstats_compat::pg::{self as cpg, TestDb};
use devstats_compat::{
    fixture, go_binary, mask_go_durations, run, rust_binary, Invocation, Outcome,
};
use tempfile::TempDir;

fn go_bin() -> Option<PathBuf> {
    go_binary("reconcile_dbs")
}

fn rust_bin() -> PathBuf {
    rust_binary(env!("CARGO_BIN_EXE_reconcile_dbs"))
}

/// `Invocation` borrows its environment; the handful of strings per case are
/// simply leaked for the life of the test process.
fn leak(s: &str) -> &'static str {
    Box::leak(s.to_string().into_boxed_str())
}

/// The build-information line every DevStats tool prints when it first logs.
const BANNER: &str = "Compiled None, commit: None on None using None";

/// First artificial event id (2^48).
const ARTIFICIAL_BASE: i64 = 281_474_976_710_656;

/// The targeted post-processing scripts `RunEventIDsPostprocessDB` reads
/// from `util_sql/` (copied from the `get_repos` fixtures).
const UTIL_SQL: &[&str] = &[
    "postprocess_texts_ids.sql",
    "postprocess_labels_ids.sql",
    "postprocess_issues_prs_ids.sql",
];

// ---------------------------------------------------------------------------
// The world: repositories, dimension rows and events
// ---------------------------------------------------------------------------

const SHA_A: &str = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
const SHA_B: &str = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";
const SHA_C: &str = "cccccccccccccccccccccccccccccccccccccccc";
const SHA_D: &str = "dddddddddddddddddddddddddddddddddddddddd";
const SHA_E: &str = "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee";
const SHA_V: &str = "5555555555555555555555555555555555555555";
const SHA_W: &str = "6666666666666666666666666666666666666666";
const SHA_X: &str = "7777777777777777777777777777777777777777";
const SHA_Y: &str = "8888888888888888888888888888888888888888";
const SHA_Z: &str = "9999999999999999999999999999999999999999";

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Kind {
    /// `WatchEvent`: only `gha_events` + `gha_payloads`.
    Plain,
    /// `PushEvent` with these commits (`gha_commits` + two
    /// `gha_commits_roles` rows each).
    Push(&'static [&'static str]),
    /// `IssuesEvent` #7 with label 5 (`bug`) and a comment.
    Issue,
    /// `PullRequestEvent` #7 with a review.
    Pr,
}

#[derive(Clone, Copy, Debug)]
struct Ev {
    id: i64,
    repo: i64,
    /// Days before "today" (`created_at` is that day at 10:00:00).
    days_ago: i64,
    kind: Kind,
}

const fn ev(id: i64, repo: i64, days_ago: i64, kind: Kind) -> Ev {
    Ev {
        id,
        repo,
        days_ago,
        kind,
    }
}

// Main world (repositories 101, 102, 104 in the target; 103 only in the source).
/// Common event (both databases).
const E1: Ev = ev(1001, 101, 10, Kind::Plain);
/// Native push missing in the target.
const E2: Ev = ev(1002, 101, 10, Kind::Push(&[SHA_A]));
/// Native issue (#7, label `bug`, one comment) missing in the target.
const E3: Ev = ev(1003, 102, 5, Kind::Issue);
/// Older than the default 90 days window.
const E4: Ev = ev(1004, 101, 100, Kind::Push(&[SHA_D]));
/// Repository 103 is not in the target: out of scope.
const E5: Ev = ev(1005, 103, 3, Kind::Push(&[SHA_E]));
/// Repository without an organization.
const E6: Ev = ev(1006, 104, 2, Kind::Plain);
/// Native pull request #7 (links to the issue #7 of E3) missing in the target.
const E7: Ev = ev(1007, 102, 5, Kind::Pr);
/// Artificial event.
const A1: Ev = ev(ARTIFICIAL_BASE + 1, 101, 3, Kind::Plain);
/// Orphan (restored) push whose commit the target already has (under T1).
const O1: Ev = ev(-5001, 101, 4, Kind::Push(&[SHA_B]));
/// Orphan push with a new commit.
const O2: Ev = ev(-5002, 102, 4, Kind::Push(&[SHA_C]));
/// Target-only native push (commit B).
const T1: Ev = ev(1000, 101, 12, Kind::Push(&[SHA_B]));

// Takeover world.
/// Synthetic push in the target with commit X (emptied by the takeover).
const S1: Ev = ev(-6001, 101, 6, Kind::Push(&[SHA_X]));
/// Synthetic push in the target with commits Y and Z (Z stays).
const S2: Ev = ev(-6002, 101, 6, Kind::Push(&[SHA_Y, SHA_Z]));
/// Native push in both databases with commit W.
const T2: Ev = ev(1020, 101, 7, Kind::Push(&[SHA_W]));
/// Native pushes missing in the target: X+V, Y+V, W.
const N1: Ev = ev(1010, 101, 6, Kind::Push(&[SHA_X, SHA_V]));
const N2: Ev = ev(1011, 101, 6, Kind::Push(&[SHA_Y, SHA_V]));
const N3: Ev = ev(1012, 101, 7, Kind::Push(&[SHA_W]));

fn repo_name(repo: i64) -> &'static str {
    match repo {
        101 => "org1/repo1",
        102 => "org1/repo2",
        103 => "org2/repo3",
        104 => "solo/repo4",
        201 => "other/repo",
        _ => panic!("unknown repository {repo}"),
    }
}

/// `(org_id, org_login)` of a repository (`None`: no organization).
fn repo_org(repo: i64) -> Option<(i64, &'static str)> {
    match repo {
        101 | 102 => Some((11, "org1")),
        103 => Some((12, "org2")),
        _ => None,
    }
}

/// Actor of an event: even ids are `bob` (22), odd ids `alice` (21).
fn actor(id: i64) -> (i64, &'static str) {
    if id.rem_euclid(2) == 0 {
        (22, "bob")
    } else {
        (21, "alice")
    }
}

fn kind_type(kind: Kind) -> &'static str {
    match kind {
        Kind::Plain => "WatchEvent",
        Kind::Push(_) => "PushEvent",
        Kind::Issue => "IssuesEvent",
        Kind::Pr => "PullRequestEvent",
    }
}

fn sql_opt(v: Option<i64>) -> String {
    v.map_or("null".to_string(), |v| v.to_string())
}

/// A database's contents.
#[derive(Clone, Debug, Default)]
struct Db {
    repos: Vec<i64>,
    orgs: Vec<i64>,
    labels: Vec<i64>,
    actors: Vec<i64>,
    events: Vec<Ev>,
    /// Events with a `gha_texts` row (the target needs a non-empty
    /// `gha_texts` for the targeted post-processing to run).
    texts_for: Vec<i64>,
    /// Events with a `gha_events_commits_files` row (synthetic restores).
    ecf_for: Vec<i64>,
}

impl Db {
    fn new(repos: &[i64], orgs: &[i64], labels: &[i64], actors: &[i64], events: &[Ev]) -> Self {
        Db {
            repos: repos.to_vec(),
            orgs: orgs.to_vec(),
            labels: labels.to_vec(),
            actors: actors.to_vec(),
            events: events.to_vec(),
            texts_for: Vec::new(),
            ecf_for: Vec::new(),
        }
    }
    fn texts(mut self, ids: &[i64]) -> Self {
        self.texts_for = ids.to_vec();
        self
    }
    fn ecf(mut self, ids: &[i64]) -> Self {
        self.ecf_for = ids.to_vec();
        self
    }
    fn event(&self, id: i64) -> Ev {
        *self
            .events
            .iter()
            .find(|e| e.id == id)
            .unwrap_or_else(|| panic!("event {id} not in this database"))
    }
}

/// The main-world source (everything) and target (E1 + T1, texts for T1).
fn main_source() -> Db {
    Db::new(
        &[101, 102, 103, 104],
        &[11, 12],
        &[5, 6],
        &[21, 22],
        &[E1, E2, E3, E4, E5, E6, E7, A1, O1, O2],
    )
}

fn main_target() -> Db {
    Db::new(&[101, 102, 104], &[11], &[], &[21], &[E1, T1]).texts(&[T1.id])
}

/// `'YYYY-MM-DD HH:00:00'` of `days_ago` days before `today` at `hour`.
fn ts(today: NaiveDate, days_ago: i64, hour: u32) -> String {
    format!(
        "'{} {hour:02}:00:00'",
        (today - Duration::days(days_ago)).format("%Y-%m-%d")
    )
}

fn commit_sql(e: &Ev, sha: &str, created: &str) -> String {
    let (aid, login) = actor(e.id);
    let name = repo_name(e.repo);
    format!(
        "insert into gha_commits(sha, event_id, author_name, message, is_distinct, dup_actor_id, dup_actor_login, dup_repo_id, dup_repo_name, dup_type, dup_created_at, author_email, committer_name, committer_email, author_id, committer_id, dup_author_login, dup_committer_login, loc_added, loc_removed, files_changed, origin, inserted_at) \
         values ('{sha}', {id}, 'Author {login}', 'commit {short} of {id}', true, {aid}, '{login}', {repo}, '{name}', 'PushEvent', {created}, '{login}@example.com', 'Committer {login}', '{login}-c@example.com', {aid}, {aid}, '{login}', '{login}', 10, 2, 1, 0, '2025-01-01 00:00:00');\n\
         insert into gha_commits_roles(sha, event_id, role, actor_id, actor_login, actor_name, actor_email, dup_repo_id, dup_repo_name, dup_created_at) \
         values ('{sha}', {id}, 'author', {aid}, '{login}', 'Author {login}', '{login}@example.com', {repo}, '{name}', {created}), \
         ('{sha}', {id}, 'committer', {aid}, '{login}', 'Committer {login}', '{login}-c@example.com', {repo}, '{name}', {created});\n",
        id = e.id,
        repo = e.repo,
        short = &sha[..7],
    )
}

fn event_sql(today: NaiveDate, e: &Ev) -> String {
    let created = ts(today, e.days_ago, 10);
    let (aid, login) = actor(e.id);
    let name = repo_name(e.repo);
    let org = sql_opt(repo_org(e.repo).map(|(id, _)| id));
    let typ = kind_type(e.kind);
    let mut sql = format!(
        "insert into gha_events(id, type, actor_id, repo_id, created_at, org_id, dup_actor_login, dup_repo_name) \
         values ({id}, '{typ}', {aid}, {repo}, {created}, {org}, '{login}', '{name}');\n",
        id = e.id,
        repo = e.repo,
    );
    let (push_id, size, refname, head, befor, action, issue_id, pr_id, number) = match e.kind {
        Kind::Push(shas) => (
            format!("{}", e.id.abs() * 10),
            shas.len().to_string(),
            "'refs/heads/main'".to_string(),
            format!("'{}'", shas[0]),
            "'0000000000000000000000000000000000000000'".to_string(),
            "null".to_string(),
            "null".to_string(),
            "null".to_string(),
            "null".to_string(),
        ),
        Kind::Issue => (
            "null".into(),
            "null".into(),
            "null".into(),
            "null".into(),
            "null".into(),
            "'opened'".into(),
            (70000 + e.id).to_string(),
            "null".into(),
            "7".into(),
        ),
        Kind::Pr => (
            "null".into(),
            "null".into(),
            "null".into(),
            "null".into(),
            "null".into(),
            "'opened'".into(),
            "null".into(),
            (80000 + e.id).to_string(),
            "7".into(),
        ),
        Kind::Plain => (
            "null".into(),
            "null".into(),
            "null".into(),
            "null".into(),
            "null".into(),
            "'started'".into(),
            "null".into(),
            "null".into(),
            "null".into(),
        ),
    };
    sql += &format!(
        "insert into gha_payloads(event_id, push_id, size, ref, head, befor, action, issue_id, pull_request_id, comment_id, number, forkee_id, release_id, member_id, commit, dup_actor_login, dup_repo_id, dup_repo_name, dup_type, dup_created_at) \
         values ({id}, {push_id}, {size}, {refname}, {head}, {befor}, {action}, {issue_id}, {pr_id}, null, {number}, null, null, null, null, '{login}', {repo}, '{name}', '{typ}', {created});\n",
        id = e.id,
        repo = e.repo,
    );
    match e.kind {
        Kind::Push(shas) => {
            for sha in shas {
                sql += &commit_sql(e, sha, &created);
            }
        }
        Kind::Issue => {
            let iid = 70000 + e.id;
            sql += &format!(
                "insert into gha_issues(id, event_id, assignee_id, body, closed_at, comments, created_at, locked, milestone_id, number, state, title, updated_at, user_id, is_pull_request, dup_actor_id, dup_actor_login, dup_repo_id, dup_repo_name, dup_type, dup_created_at, dup_user_login) \
                 values ({iid}, {id}, null, 'Issue body {id}', null, 1, {created}, false, null, 7, 'open', 'Issue title {id}', {created}, {aid}, false, {aid}, '{login}', {repo}, '{name}', '{typ}', {created}, '{login}');\n\
                 insert into gha_issues_labels(issue_id, event_id, label_id, dup_actor_id, dup_actor_login, dup_repo_id, dup_repo_name, dup_type, dup_created_at, dup_issue_number, dup_label_name) \
                 values ({iid}, {id}, 5, {aid}, '{login}', {repo}, '{name}', '{typ}', {created}, 7, 'bug');\n\
                 insert into gha_comments(id, event_id, body, created_at, updated_at, user_id, commit_id, original_commit_id, position, original_position, path, pull_request_review_id, line, dup_actor_id, dup_actor_login, dup_repo_id, dup_repo_name, dup_type, dup_created_at, dup_user_login) \
                 values ({cid}, {id}, 'Comment body {id}', {created}, {created}, {aid}, null, null, null, null, null, null, null, {aid}, '{login}', {repo}, '{name}', '{typ}', {created}, '{login}');\n",
                id = e.id,
                repo = e.repo,
                cid = 90000 + e.id,
            );
        }
        Kind::Pr => {
            let pid = 80000 + e.id;
            sql += &format!(
                "insert into gha_pull_requests(id, event_id, user_id, base_sha, head_sha, merged_by_id, assignee_id, milestone_id, number, state, locked, title, body, created_at, updated_at, closed_at, merged_at, merge_commit_sha, merged, mergeable, rebaseable, mergeable_state, comments, review_comments, maintainer_can_modify, commits, additions, deletions, changed_files, dup_actor_id, dup_actor_login, dup_repo_id, dup_repo_name, dup_type, dup_created_at, dup_user_login, dupn_merged_by_login) \
                 values ({pid}, {id}, {aid}, '{SHA_A}', '{SHA_C}', null, null, null, 7, 'open', false, 'PR title {id}', 'PR body {id}', {created}, {created}, null, null, null, false, true, true, 'clean', 0, 1, true, 1, 10, 2, 1, {aid}, '{login}', {repo}, '{name}', '{typ}', {created}, '{login}', null);\n\
                 insert into gha_reviews(id, user_id, commit_id, submitted_at, author_association, state, body, event_id, dup_actor_id, dup_actor_login, dup_repo_id, dup_repo_name, dup_type, dup_created_at, dup_user_login) \
                 values ({rid}, {aid}, '{SHA_C}', {created}, 'MEMBER', 'APPROVED', 'Review body {id}', {id}, {aid}, '{login}', {repo}, '{name}', '{typ}', {created}, '{login}');\n",
                id = e.id,
                repo = e.repo,
                rid = 60000 + e.id,
            );
        }
        Kind::Plain => {}
    }
    sql
}

/// Seed SQL of a database (dimension rows, events and their rows, texts and
/// commit files of the listed events).
fn seed_sql(today: NaiveDate, db: &Db) -> String {
    let mut sql = String::new();
    for repo in &db.repos {
        let (org_id, org_login) = match repo_org(*repo) {
            Some((id, login)) => (id.to_string(), format!("'{login}'")),
            None => ("null".to_string(), "null".to_string()),
        };
        sql += &format!(
            "insert into gha_repos(id, name, org_id, org_login, repo_group, alias) values ({repo}, '{name}', {org_id}, {org_login}, 'group-{repo}', '{name}');\n",
            name = repo_name(*repo),
        );
    }
    for org in &db.orgs {
        let login = match org {
            11 => "org1",
            12 => "org2",
            _ => panic!("unknown organization {org}"),
        };
        sql += &format!("insert into gha_orgs(id, login) values ({org}, '{login}');\n");
    }
    for label in &db.labels {
        let (name, color, def) = match label {
            5 => ("bug", "ff0000", "true"),
            6 => ("feature", "00ff00", "false"),
            _ => panic!("unknown label {label}"),
        };
        sql += &format!(
            "insert into gha_labels(id, name, color, is_default) values ({label}, '{name}', '{color}', {def});\n"
        );
    }
    for actor in &db.actors {
        let (login, name) = match actor {
            21 => ("alice", "Alice"),
            22 => ("bob", "Bob"),
            _ => panic!("unknown actor {actor}"),
        };
        sql += &format!(
            "insert into gha_actors(id, login, name, country_id, sex, sex_prob, tz, tz_offset, country_name, age) values ({actor}, '{login}', '{name}', 'pl', 'm', 0.75, 'Europe/Warsaw', 60, 'Poland', 40);\n"
        );
    }
    for e in &db.events {
        sql += &event_sql(today, e);
    }
    for id in &db.texts_for {
        let e = db.event(*id);
        let created = ts(today, e.days_ago, 10);
        let (aid, login) = actor(e.id);
        sql += &format!(
            "insert into gha_texts(event_id, body, created_at, actor_id, actor_login, repo_id, repo_name, type) values ({id}, 'text of {id}', {created}, {aid}, '{login}', {repo}, '{name}', '{typ}');\n",
            repo = e.repo,
            name = repo_name(e.repo),
            typ = kind_type(e.kind),
        );
    }
    for id in &db.ecf_for {
        let e = db.event(*id);
        let created = ts(today, e.days_ago, 10);
        let Kind::Push(shas) = e.kind else {
            panic!("commit files need a push event: {id}");
        };
        for sha in shas {
            sql += &format!(
                "insert into gha_events_commits_files(sha, event_id, path, size, dt, repo_group, dup_repo_id, dup_repo_name, ext) values ('{sha}', {id}, 'src/{short}.go', 100, {created}, null, {repo}, '{name}', 'go');\n",
                short = &sha[..7],
                repo = e.repo,
                name = repo_name(e.repo),
            );
        }
    }
    sql
}

// ---------------------------------------------------------------------------
// Harness
// ---------------------------------------------------------------------------

struct Case {
    name: &'static str,
    /// Databases by key; `tgt` is the target (`PG_DB`). `None`: the
    /// database is created with the schema only.
    dbs: Vec<(&'static str, Option<Db>)>,
    /// Database keys listed but **not** created (missing databases).
    missing: Vec<&'static str>,
    /// `projects.yaml` written to the scratch directory (`{db:key}`
    /// placeholders expand to the side's database names).
    yaml: Option<&'static str>,
    /// `GHA2DB_LOCAL=1` (files from the working directory); otherwise
    /// `GHA2DB_DATADIR=<scratch dir>`.
    local: bool,
    /// Extra environment (`{db:key}` placeholders in the values).
    env: Vec<(&'static str, &'static str)>,
    /// Number of consecutive runs (all compared).
    runs: usize,
}

impl Case {
    fn new(name: &'static str) -> Self {
        Case {
            name,
            dbs: Vec::new(),
            missing: Vec::new(),
            yaml: None,
            local: true,
            env: Vec::new(),
            runs: 1,
        }
    }
    /// The main world: `tgt` + `src`, explicit mode.
    fn main(name: &'static str) -> Self {
        Case::new(name)
            .db("tgt", main_target())
            .db("src", main_source())
            .env("GHA2DB_RECONCILE_DBS", "{db:src}")
    }
    fn db(mut self, key: &'static str, db: Db) -> Self {
        self.dbs.retain(|(k, _)| *k != key);
        self.dbs.push((key, Some(db)));
        self
    }
    fn empty_db(mut self, key: &'static str) -> Self {
        self.dbs.retain(|(k, _)| *k != key);
        self.dbs.push((key, None));
        self
    }
    fn missing(mut self, key: &'static str) -> Self {
        self.missing.push(key);
        self
    }
    fn yaml(mut self, y: &'static str) -> Self {
        self.yaml = Some(y);
        self
    }
    fn datadir(mut self) -> Self {
        self.local = false;
        self
    }
    fn env(mut self, k: &'static str, v: &'static str) -> Self {
        self.env.retain(|(key, _)| *key != k);
        self.env.push((k, v));
        self
    }
    fn no_env(mut self, k: &'static str) -> Self {
        self.env.retain(|(key, _)| *key != k);
        self
    }
    fn runs(mut self, n: usize) -> Self {
        self.runs = n;
        self
    }
}

struct Side {
    dbs: BTreeMap<String, TestDb>,
    /// Database name prefix of the side (masked in the outputs).
    prefix: String,
    dir: TempDir,
    outs: Vec<Outcome>,
}

impl Side {
    fn mask(&self, s: &str) -> String {
        let s = s
            .replace(&self.prefix, "<dbs>_")
            .replace(&self.dir.path().display().to_string(), "<dir>");
        // `since 2026-09-17 07:53:19 (range` — the header's window start;
        // `[1:2026-09-17 07:53:19 2:90 days ]` — the arguments echo of a
        // failing `GetDateAgo` query.
        let mut out = String::new();
        for (i, line) in s.lines().enumerate() {
            if i > 0 {
                out.push('\n');
            }
            match (line.find(", since "), line.find(" (range ")) {
                (Some(a), Some(b)) if a < b => {
                    out.push_str(&line[..a + 8]);
                    out.push_str("<since>");
                    out.push_str(&line[b..]);
                }
                _ if line.starts_with("[1:20") && line.len() > 22 => {
                    out.push_str("[1:<time>");
                    out.push_str(&line[22..]);
                }
                _ => out.push_str(line),
            }
        }
        out
    }
    /// Masked stdout lines of run `i`.
    fn stdout_lines(&self, i: usize) -> Vec<String> {
        self.mask(&mask_go_durations(&self.outs[i].stdout_str()))
            .lines()
            .map(str::to_string)
            .collect()
    }
    /// The stdout lines of run `i` without the banner.
    fn lines_of(&self, i: usize) -> Vec<String> {
        self.stdout_lines(i)
            .into_iter()
            .filter(|l| l != BANNER)
            .collect()
    }
    /// The stdout lines of the first run without the banner.
    fn lines(&self) -> Vec<String> {
        self.lines_of(0)
    }
    fn code(&self) -> Option<i32> {
        self.outs[0].code
    }
    fn has_line(&self, line: &str) -> bool {
        self.lines().iter().any(|l| l == line)
    }
    fn has_line_starting(&self, prefix: &str) -> bool {
        self.lines().iter().any(|l| l.starts_with(prefix))
    }
    fn stderr_lines(&self, i: usize) -> Vec<String> {
        self.outs[i]
            .stderr_str()
            .lines()
            .filter(|l| l.starts_with("Error: '") || l.starts_with("PqError: "))
            .map(|l| self.mask(l))
            .collect()
    }
    /// The `Error: '…'` message of a fatal error (first run).
    fn error(&self) -> Option<String> {
        self.stderr_lines(0).into_iter().find_map(|l| {
            l.strip_prefix("Error: '")
                .and_then(|r| r.strip_suffix('\''))
                .map(str::to_string)
        })
    }
    /// Every table of the target database (rows ordered by all columns;
    /// `gha_repos` without its `now()`-defaulted timestamps).
    fn data(&self) -> BTreeMap<String, Vec<Vec<String>>> {
        let mut res = BTreeMap::new();
        if let Some(db) = self.dbs.get("tgt") {
            let con = db.conn();
            for t in cpg::tables(&con) {
                let snap = if t == "gha_repos" {
                    cpg::snapshot(
                        &con,
                        "select id, name, org_id, org_login, repo_group, alias from gha_repos order by 1, 2, 3, 4, 5, 6",
                        &[],
                    )
                } else {
                    cpg::table_data(&con, &t)
                };
                res.insert(t, snap.rows);
            }
            con.close();
        }
        res
    }
    /// Sorted single-column query result on the target database.
    fn query(&self, sql: &str) -> Vec<String> {
        let con = self.dbs["tgt"].conn();
        let snap = cpg::snapshot(&con, sql, &[]);
        con.close();
        snap.column(0)
    }
    fn count(&self, table: &str) -> i64 {
        self.query(&format!("select count(*) from {table}"))[0]
            .parse()
            .unwrap()
    }
    /// Sorted event ids of the target.
    fn event_ids(&self) -> Vec<i64> {
        self.query("select id from gha_events order by id")
            .iter()
            .map(|s| s.parse().unwrap())
            .collect()
    }
    /// `(sha, event_id, is_distinct)` rows of the target's `gha_commits`.
    fn commits(&self) -> Vec<(String, i64, bool)> {
        let con = self.dbs["tgt"].conn();
        let snap = cpg::snapshot(
            &con,
            "select sha, event_id, is_distinct from gha_commits order by sha, event_id",
            &[],
        );
        con.close();
        snap.rows
            .iter()
            .map(|r| (r[0].clone(), r[1].parse().unwrap(), r[2] == "true"))
            .collect()
    }
}

/// Expand `{db:key}` placeholders to `<prefix><key>`.
fn expand(text: &str, prefix: &str) -> String {
    let mut text = text.to_string();
    while let Some(start) = text.find("{db:") {
        let end = text[start..].find('}').unwrap() + start;
        let key = text[start + 4..end].to_string();
        text.replace_range(start..=end, &format!("{prefix}{key}"));
    }
    text
}

fn run_side(bin: &Path, case: &Case, suffix: &str, today: NaiveDate) -> Option<Side> {
    let short = format!("reconcile_{}_{}_", case.name, suffix);
    let prefix = format!("{}_{}", cpg::GUARD_DB, short);
    let schema = fs::read_to_string(fixture("structure/full_structure.sql")).unwrap();
    let mut dbs = BTreeMap::new();
    for (key, contents) in &case.dbs {
        let db = TestDb::fresh(&format!("{short}{key}"))?;
        db.exec(&schema);
        if let Some(contents) = contents {
            db.exec(&seed_sql(today, contents));
        }
        dbs.insert(key.to_string(), db);
    }
    for key in &case.missing {
        // Created and dropped right away: the handle only guarantees the
        // name is free (and cleans up whatever a bug might create there).
        let db = TestDb::absent(&format!("{short}{key}"))?;
        dbs.insert(key.to_string(), db);
    }
    let dir = tempfile::Builder::new()
        .prefix(&format!("g2r_{short}"))
        .tempdir()
        .unwrap();
    if let Some(y) = case.yaml {
        fs::write(dir.path().join("projects.yaml"), expand(y, &prefix)).unwrap();
    }
    fs::create_dir(dir.path().join("util_sql")).unwrap();
    for script in UTIL_SQL {
        fs::copy(
            fixture(&format!("get_repos/util_sql/{script}")),
            dir.path().join("util_sql").join(script),
        )
        .unwrap();
    }

    let mut env: Vec<(String, String)> = dbs["tgt"]
        .env()
        .into_iter()
        .map(|(k, v)| (k.to_string(), v.to_string()))
        .collect();
    if case.local {
        env.push(("GHA2DB_LOCAL".into(), "1".into()));
    } else {
        env.push(("GHA2DB_DATADIR".into(), dir.path().display().to_string()));
    }
    for (k, v) in &case.env {
        env.retain(|(key, _)| key != k);
        env.push((k.to_string(), expand(v, &prefix)));
    }
    let mut inv = Invocation::new().cwd(dir.path().to_path_buf());
    for (k, v) in &env {
        inv = inv.env(leak(k), leak(v));
    }
    let outs = (0..case.runs).map(|_| run(bin, &inv)).collect();
    Some(Side {
        dbs,
        prefix,
        dir,
        outs,
    })
}

/// Run both binaries and compare everything; returns the Rust side for
/// further assertions (`None` when the DB tests are skipped).
fn both(case: &Case) -> Option<Side> {
    let today = Utc::now().date_naive();
    let rust = run_side(&rust_bin(), case, "rs", today)?;
    if let Some(go) = go_bin() {
        let go = run_side(&go, case, "go", today).unwrap();
        for i in 0..case.runs {
            let ctx = format!(
                "\ncase {:?} run {i} env {:?}\n--- go code {:?} stdout:\n{}--- go stderr:\n{}--- rust code {:?} stdout:\n{}--- rust stderr:\n{}",
                case.name,
                case.env,
                go.outs[i].code,
                go.outs[i].stdout_str(),
                go.outs[i].stderr_str(),
                rust.outs[i].code,
                rust.outs[i].stdout_str(),
                rust.outs[i].stderr_str(),
            );
            assert_eq!(go.outs[i].code, rust.outs[i].code, "exit code{ctx}");
            assert_eq!(go.stdout_lines(i), rust.stdout_lines(i), "stdout{ctx}");
            assert_eq!(go.stderr_lines(i), rust.stderr_lines(i), "stderr{ctx}");
        }
        assert_eq!(go.data(), rust.data(), "target database contents");
    }
    Some(rust)
}

/// The per-source line prefix of the main world.
const P: &str = "reconcile_dbs: <dbs>_tgt <- <dbs>_src";

fn header(mode: &str, sources: &str, range: &str, classes: &str, dry: bool) -> String {
    let n = sources.split(", ").count();
    format!(
        "reconcile_dbs: <dbs>_tgt: mode {mode}, {n} source(s): {sources}, since <since> (range '{range}'), classes: {classes}, dry run: {dry}"
    )
}

/// The filter line of a run without a projects.yaml (explicit mode, local).
const NO_FILTER: &str = "reconcile_dbs: <dbs>_tgt: filter: none (no ./projects.yaml)";

/// The filter line of a run whose target belongs to `project`.
fn filter_line(project: &str, orgs: &str, repos: &str, excluded: usize, actors: bool) -> String {
    format!(
        "reconcile_dbs: <dbs>_tgt: filter: project '{project}': {orgs}, {repos}, {excluded} excluded repo(s), exact false, actors filter {actors}"
    )
}

// ---------------------------------------------------------------------------
// Explicit mode: copying, re-runs, orphans, dimensions, post-processing
// ---------------------------------------------------------------------------

#[test]
fn explicit_copies_the_missing_events_and_is_idempotent() {
    let Some(rs) = both(&Case::main("explicit").runs(2)) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    let lines = rs.lines();
    assert_eq!(
        lines,
        [
            header(
                "explicit (GHA2DB_RECONCILE_DBS)",
                "<dbs>_src",
                "90 days",
                "native, orphan",
                false
            ),
            NO_FILTER.to_string(),
            format!("{P}: scope 3 repo(s) (target 3, source 4)"),
            // Only the source's buckets matter (T1's day is target-only).
            format!("{P}: buckets: source 5, target 2, differing 5"),
            format!("{P}: events: source-only 6 (native 4, orphan 2, artificial 0), target-only 0"),
            format!("{P}: skipped 1 orphan event(s) whose commits are already present"),
            format!("{P}: table gha_events: rows 5, inserted 5"),
            format!("{P}: table gha_payloads: rows 5, inserted 5"),
            format!("{P}: table gha_commits: rows 2, inserted 2"),
            format!("{P}: table gha_commits_roles: rows 4, inserted 4"),
            format!("{P}: table gha_comments: rows 1, inserted 1"),
            format!("{P}: table gha_issues: rows 1, inserted 1"),
            format!("{P}: table gha_issues_labels: rows 1, inserted 1"),
            format!("{P}: table gha_pull_requests: rows 1, inserted 1"),
            format!("{P}: table gha_reviews: rows 1, inserted 1"),
            format!("{P}: table gha_repos: rows 3, inserted 0"),
            format!("{P}: table gha_orgs: rows 1, inserted 0"),
            format!("{P}: table gha_labels: rows 1, inserted 1"),
            format!("{P}: table gha_actors: rows 2, inserted 1"),
            format!("{P}: copied 5 event(s), inserted 23 row(s), postprocess 5 event id(s)"),
            "targeted postprocess executed for 5 restored event id(s)".to_string(),
            "reconcile_dbs: <dbs>_tgt: 1 source(s), copied 5 event(s), inserted 23 row(s), filtered out 0 event(s), skipped 1 orphan event(s), taken over 0 commit(s)".to_string(),
            "Time: <duration>".to_string(),
        ]
    );
    // Second run: only the skipped orphan's day still differs.
    assert_eq!(rs.outs[1].code, Some(0));
    assert_eq!(
        rs.lines_of(1),
        [
            header(
                "explicit (GHA2DB_RECONCILE_DBS)",
                "<dbs>_src",
                "90 days",
                "native, orphan",
                false
            ),
            NO_FILTER.to_string(),
            format!("{P}: scope 3 repo(s) (target 3, source 4)"),
            format!("{P}: buckets: source 5, target 5, differing 1"),
            format!("{P}: events: source-only 1 (native 0, orphan 1, artificial 0), target-only 0"),
            format!("{P}: skipped 1 orphan event(s) whose commits are already present"),
            "reconcile_dbs: <dbs>_tgt: 1 source(s), copied 0 event(s), inserted 0 row(s), filtered out 0 event(s), skipped 1 orphan event(s), taken over 0 commit(s)".to_string(),
            "Time: <duration>".to_string(),
        ]
    );
    // Target contents: the window, class, scope and orphan rules.
    assert_eq!(
        rs.event_ids(),
        [O2.id, T1.id, E1.id, E2.id, E3.id, E6.id, E7.id]
    );
    assert_eq!(
        rs.commits(),
        [
            (SHA_A.to_string(), E2.id, true),
            (SHA_B.to_string(), T1.id, true),
            (SHA_C.to_string(), O2.id, true),
        ]
    );
    assert_eq!(rs.count("gha_commits_roles"), 6);
    // Dimensions: the referenced label and actor were added, the
    // repositories kept their groups, nothing else was touched.
    assert_eq!(rs.query("select id from gha_labels order by id"), ["5"]);
    assert_eq!(
        rs.query("select login from gha_actors order by id"),
        ["alice", "bob"]
    );
    assert_eq!(
        rs.query("select id || ':' || coalesce(repo_group, '<null>') from gha_repos order by id"),
        ["101:group-101", "102:group-102", "104:group-104"]
    );
    assert_eq!(rs.query("select id from gha_orgs order by id"), ["11"]);
    // Targeted post-processing: texts of the copied rows, the issue's
    // label event and the issue <-> PR link.
    assert_eq!(
        rs.query("select event_id || ':' || body from gha_texts order by event_id, body"),
        [
            format!("{}:commit ccccccc of {}", O2.id, O2.id),
            format!("{}:text of {}", T1.id, T1.id),
            format!("{}:commit aaaaaaa of {}", E2.id, E2.id),
            format!("{}:Comment body {}", E3.id, E3.id),
            format!("{}:Issue body {}", E3.id, E3.id),
            format!("{}:Issue title {}", E3.id, E3.id),
            format!("{}:PR body {}", E7.id, E7.id),
            format!("{}:PR title {}", E7.id, E7.id),
            format!("{}:Review body {}", E7.id, E7.id),
        ]
    );
    assert_eq!(
        rs.query(
            "select issue_id || ':' || event_id || ':' || label_name from gha_issues_events_labels"
        ),
        [format!("{}:{}:bug", 70000 + E3.id, E3.id)]
    );
    assert_eq!(
        rs.query("select issue_id || ':' || pull_request_id || ':' || number from gha_issues_pull_requests"),
        [format!("{}:{}:7", 70000 + E3.id, 80000 + E7.id)]
    );
}

#[test]
fn orphan_with_a_new_commit_is_copied_and_a_known_commit_is_skipped() {
    // Only the orphans differ: the target has all the native events.
    let target = Db::new(
        &[101, 102, 104],
        &[11],
        &[5],
        &[21, 22],
        &[E1, E2, E3, E6, E7, T1],
    )
    .texts(&[T1.id]);
    let Some(rs) = both(&Case::main("orphans").db("tgt", target)) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert!(rs.has_line(&format!(
        "{P}: events: source-only 2 (native 0, orphan 2, artificial 0), target-only 0"
    )));
    assert!(rs.has_line(&format!(
        "{P}: skipped 1 orphan event(s) whose commits are already present"
    )));
    assert!(rs.has_line(&format!("{P}: table gha_commits: rows 1, inserted 1")));
    assert!(rs.has_line(&format!(
        "{P}: copied 1 event(s), inserted 5 row(s), postprocess 1 event id(s)"
    )));
    assert!(rs.event_ids().contains(&O2.id));
    assert!(!rs.event_ids().contains(&O1.id));
    assert_eq!(
        rs.query("select count(*) from gha_commits where sha = $$bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb$$"),
        ["1"]
    );
}

#[test]
fn every_orphan_skipped_leaves_nothing_to_copy() {
    // The only missing event is O1 whose commit the target already has.
    let target = Db::new(
        &[101, 102, 104],
        &[11],
        &[5],
        &[21, 22],
        &[E1, E2, E3, E6, E7, T1, O2],
    )
    .texts(&[T1.id]);
    let Some(rs) = both(&Case::main("allskipped").db("tgt", target)) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert!(rs.has_line(&format!(
        "{P}: events: source-only 1 (native 0, orphan 1, artificial 0), target-only 0"
    )));
    assert!(rs.has_line(&format!(
        "{P}: skipped 1 orphan event(s) whose commits are already present"
    )));
    assert!(!rs.has_line_starting(&format!("{P}: table ")));
    assert!(rs.has_line(
        "reconcile_dbs: <dbs>_tgt: 1 source(s), copied 0 event(s), inserted 0 row(s), filtered out 0 event(s), skipped 1 orphan event(s), taken over 0 commit(s)"
    ));
}

#[test]
fn identical_databases_have_nothing_to_reconcile() {
    let Some(rs) = both(&Case::main("same").db("tgt", main_source())) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert_eq!(
        rs.lines(),
        [
            header(
                "explicit (GHA2DB_RECONCILE_DBS)",
                "<dbs>_src",
                "90 days",
                "native, orphan",
                false
            ),
            NO_FILTER.to_string(),
            format!("{P}: scope 4 repo(s) (target 4, source 4)"),
            format!("{P}: buckets: source 6, target 6, differing 0"),
            "reconcile_dbs: <dbs>_tgt: 1 source(s), copied 0 event(s), inserted 0 row(s), filtered out 0 event(s), skipped 0 orphan event(s), taken over 0 commit(s)".to_string(),
            "Time: <duration>".to_string(),
        ]
    );
}

#[test]
fn empty_target_texts_skip_the_targeted_postprocess() {
    let Some(rs) = both(&Case::main("notexts").db("tgt", main_target().texts(&[]))) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert!(rs.has_line(&format!(
        "{P}: copied 5 event(s), inserted 23 row(s), postprocess 5 event id(s)"
    )));
    assert!(rs.has_line(
        "targeted postprocess skipped: gha_texts is empty, full structure rebuild pending"
    ));
    assert_eq!(rs.count("gha_texts"), 0);
    assert_eq!(rs.count("gha_issues_events_labels"), 0);
}

#[test]
fn shared_affiliations_database_leaves_the_actors_alone() {
    let Some(rs) = both(
        &Case::main("affsdb")
            .env("GHA2DB_AFFILIATIONS_DB", "affiliations")
            .env("GHA2DB_RECONCILE_DBS", "{db:src}"),
    ) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert!(!rs.has_line_starting(&format!("{P}: table gha_actors")));
    assert!(rs.has_line(&format!("{P}: table gha_labels: rows 1, inserted 1")));
    assert!(rs.has_line(&format!(
        "{P}: copied 5 event(s), inserted 22 row(s), postprocess 5 event id(s)"
    )));
    assert_eq!(
        rs.query("select login from gha_actors order by id"),
        ["alice"]
    );
}

#[test]
fn artificial_events_need_the_flag() {
    let Some(rs) = both(
        &Case::main("artificial")
            .env("GHA2DB_RECONCILE_ARTIFICIAL", "yes")
            .env("GHA2DB_RECONCILE_DBS", "{db:src}"),
    ) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert!(rs.has_line(&header(
        "explicit (GHA2DB_RECONCILE_DBS)",
        "<dbs>_src",
        "90 days",
        "native, orphan, artificial",
        false
    )));
    assert!(rs.has_line(&format!("{P}: buckets: source 6, target 2, differing 6")));
    assert!(rs.has_line(&format!(
        "{P}: events: source-only 7 (native 4, orphan 2, artificial 1), target-only 0"
    )));
    assert!(rs.has_line(&format!("{P}: table gha_events: rows 6, inserted 6")));
    assert!(rs.has_line(&format!(
        "{P}: copied 6 event(s), inserted 25 row(s), postprocess 6 event id(s)"
    )));
    assert!(rs.event_ids().contains(&A1.id));
}

#[test]
fn explicit_source_list_is_trimmed_and_deduplicated() {
    let Some(rs) = both(&Case::main("dedup").env("GHA2DB_RECONCILE_DBS", " {db:src} ,, {db:src},"))
    else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert!(rs.has_line(&header(
        "explicit (GHA2DB_RECONCILE_DBS)",
        "<dbs>_src",
        "90 days",
        "native, orphan",
        false
    )));
    assert!(rs.has_line(
        "reconcile_dbs: <dbs>_tgt: 1 source(s), copied 5 event(s), inserted 23 row(s), filtered out 0 event(s), skipped 1 orphan event(s), taken over 0 commit(s)"
    ));
}

#[test]
fn two_explicit_sources_are_processed_in_order() {
    // src2 has the takeover-free subset of the world; the second source
    // finds everything already copied by the first.
    let src2 = Db::new(&[101, 102], &[11], &[5], &[21, 22], &[E1, E2, E3, E7]);
    let Some(rs) = both(
        &Case::main("twosrc")
            .db("src2", src2)
            .env("GHA2DB_RECONCILE_DBS", "{db:src2},{db:src}"),
    ) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    let lines = rs.lines();
    assert_eq!(
        lines[0],
        header(
            "explicit (GHA2DB_RECONCILE_DBS)",
            "<dbs>_src2, <dbs>_src",
            "90 days",
            "native, orphan",
            false
        )
    );
    assert_eq!(lines[1], NO_FILTER);
    let p2 = "reconcile_dbs: <dbs>_tgt <- <dbs>_src2";
    assert_eq!(
        lines[2],
        format!("{p2}: scope 2 repo(s) (target 3, source 2)")
    );
    assert!(rs.has_line(&format!(
        "{p2}: copied 3 event(s), inserted 16 row(s), postprocess 3 event id(s)"
    )));
    assert!(rs.has_line(&format!("{P}: scope 3 repo(s) (target 3, source 4)")));
    assert!(rs.has_line(&format!(
        "{P}: events: source-only 3 (native 1, orphan 2, artificial 0), target-only 0"
    )));
    assert!(rs.has_line(&format!(
        "{P}: copied 2 event(s), inserted 7 row(s), postprocess 2 event id(s)"
    )));
    assert!(rs.has_line(
        "reconcile_dbs: <dbs>_tgt: 2 source(s), copied 5 event(s), inserted 23 row(s), filtered out 0 event(s), skipped 1 orphan event(s), taken over 0 commit(s)"
    ));
}

// ---------------------------------------------------------------------------
// Takeover of restored commits
// ---------------------------------------------------------------------------

#[test]
fn native_pushes_take_over_the_restored_commits() {
    let target = Db::new(&[101], &[11], &[], &[21, 22], &[S1, S2, T2])
        .texts(&[S1.id, S2.id, T2.id])
        .ecf(&[S1.id, S2.id]);
    let source = Db::new(&[101], &[11], &[], &[21, 22], &[T2, N1, N2, N3]);
    let Some(rs) = both(
        &Case::new("takeover")
            .db("tgt", target)
            .db("src", source)
            .env("GHA2DB_RECONCILE_DBS", "{db:src}"),
    ) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert_eq!(
        rs.lines(),
        [
            header(
                "explicit (GHA2DB_RECONCILE_DBS)",
                "<dbs>_src",
                "90 days",
                "native, orphan",
                false
            ),
            NO_FILTER.to_string(),
            format!("{P}: scope 1 repo(s) (target 1, source 1)"),
            // Same counts on day -6 (2 vs 2) but different id sums.
            format!("{P}: buckets: source 2, target 2, differing 2"),
            format!("{P}: events: source-only 3 (native 3, orphan 0, artificial 0), target-only 2"),
            format!("{P}: table gha_events: rows 3, inserted 3"),
            format!("{P}: table gha_payloads: rows 3, inserted 3"),
            format!("{P}: table gha_commits: rows 5, inserted 5"),
            format!("{P}: table gha_commits_roles: rows 10, inserted 10"),
            format!("{P}: table gha_repos: rows 1, inserted 0"),
            format!("{P}: table gha_orgs: rows 1, inserted 0"),
            format!("{P}: table gha_actors: rows 2, inserted 0"),
            format!("{P}: taken over 2 commit(s) from 2 restored push event(s), removed 1 emptied restored event(s)"),
            format!("{P}: copied 3 event(s), inserted 21 row(s), postprocess 4 event id(s)"),
            "targeted postprocess executed for 4 restored event id(s)".to_string(),
            "reconcile_dbs: <dbs>_tgt: 1 source(s), copied 3 event(s), inserted 21 row(s), filtered out 0 event(s), skipped 0 orphan event(s), taken over 2 commit(s)".to_string(),
            "Time: <duration>".to_string(),
        ]
    );
    // S1 is gone (with its payload, text and files), S2 kept Z.
    assert_eq!(rs.event_ids(), [S2.id, N1.id, N2.id, N3.id, T2.id]);
    assert_eq!(
        rs.commits(),
        [
            // V: copied under N1 and N2 - the lowest event id is distinct.
            (SHA_V.to_string(), N1.id, true),
            (SHA_V.to_string(), N2.id, false),
            // W: T2 had it before - the copied row is not distinct.
            (SHA_W.to_string(), N3.id, false),
            (SHA_W.to_string(), T2.id, true),
            // X and Y: taken over from S1 and S2.
            (SHA_X.to_string(), N1.id, true),
            (SHA_Y.to_string(), N2.id, true),
            (SHA_Z.to_string(), S2.id, true),
        ]
    );
    assert_eq!(
        rs.query("select event_id from gha_commits_roles group by event_id order by event_id"),
        [S2.id, N1.id, N2.id, N3.id, T2.id].map(|id| id.to_string())
    );
    assert_eq!(
        rs.query(
            "select event_id || ':' || sha from gha_events_commits_files order by event_id, sha"
        ),
        [format!("{}:{SHA_Y}", S2.id), format!("{}:{SHA_Z}", S2.id)]
    );
    assert_eq!(
        rs.query("select event_id from gha_payloads order by event_id"),
        [S2.id, N1.id, N2.id, N3.id, T2.id].map(|id| id.to_string())
    );
    // Texts: S1's row is gone, S2's was rebuilt from its remaining commit,
    // T2's untouched.
    assert_eq!(
        rs.query("select event_id || ':' || body from gha_texts order by event_id, body"),
        [
            format!("{}:commit 9999999 of {}", S2.id, S2.id),
            format!("{}:commit 5555555 of {}", N1.id, N1.id),
            format!("{}:commit 7777777 of {}", N1.id, N1.id),
            format!("{}:commit 5555555 of {}", N2.id, N2.id),
            format!("{}:commit 8888888 of {}", N2.id, N2.id),
            format!("{}:commit 6666666 of {}", N3.id, N3.id),
            format!("{}:text of {}", T2.id, T2.id),
        ]
    );
}

// ---------------------------------------------------------------------------
// Dry run, window, scope
// ---------------------------------------------------------------------------

#[test]
fn dry_run_reports_without_changing_anything() {
    let Some(rs) = both(&Case::main("dryrun").env("GHA2DB_RECONCILE_DRY_RUN", "1")) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert_eq!(
        rs.lines(),
        [
            header(
                "explicit (GHA2DB_RECONCILE_DBS)",
                "<dbs>_src",
                "90 days",
                "native, orphan",
                true
            ),
            NO_FILTER.to_string(),
            format!("{P}: scope 3 repo(s) (target 3, source 4)"),
            format!("{P}: buckets: source 5, target 2, differing 5"),
            format!("{P}: events: source-only 6 (native 4, orphan 2, artificial 0), target-only 0"),
            format!("{P}: skipped 1 orphan event(s) whose commits are already present"),
            format!("{P}: table gha_events: rows 5, inserted 0"),
            format!("{P}: table gha_payloads: rows 5, inserted 0"),
            format!("{P}: table gha_commits: rows 2, inserted 0"),
            format!("{P}: table gha_commits_roles: rows 4, inserted 0"),
            format!("{P}: table gha_comments: rows 1, inserted 0"),
            format!("{P}: table gha_issues: rows 1, inserted 0"),
            format!("{P}: table gha_issues_labels: rows 1, inserted 0"),
            format!("{P}: table gha_pull_requests: rows 1, inserted 0"),
            format!("{P}: table gha_reviews: rows 1, inserted 0"),
            format!("{P}: table gha_repos: rows 3, inserted 0"),
            format!("{P}: table gha_orgs: rows 1, inserted 0"),
            format!("{P}: table gha_labels: rows 1, inserted 0"),
            format!("{P}: table gha_actors: rows 2, inserted 0"),
            format!("{P}: would copy 5 event(s), inserted 0 row(s), postprocess 5 event id(s)"),
            "reconcile_dbs: <dbs>_tgt: 1 source(s), would copy 5 event(s), inserted 0 row(s), filtered out 0 event(s), skipped 1 orphan event(s), taken over 0 commit(s)".to_string(),
            "Time: <duration>".to_string(),
        ]
    );
    assert_eq!(rs.event_ids(), [T1.id, E1.id]);
    assert_eq!(rs.count("gha_labels"), 0);
    assert_eq!(rs.count("gha_texts"), 1);
}

#[test]
fn range_limits_the_window() {
    let Some(rs) = both(&Case::main("range").env("GHA2DB_RECONCILE_RANGE", " 7 days ")) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert!(rs.has_line(&header(
        "explicit (GHA2DB_RECONCILE_DBS)",
        "<dbs>_src",
        "7 days",
        "native, orphan",
        false
    )));
    // E2 (10 days ago) is outside; E3, E7, E6, O1, O2 are inside.
    assert!(rs.has_line(&format!("{P}: buckets: source 4, target 0, differing 4")));
    assert!(rs.has_line(&format!(
        "{P}: events: source-only 5 (native 3, orphan 2, artificial 0), target-only 0"
    )));
    assert!(rs.has_line(&format!(
        "{P}: copied 4 event(s), inserted 18 row(s), postprocess 4 event id(s)"
    )));
    assert!(!rs.event_ids().contains(&E2.id));
}

#[test]
fn invalid_range_is_fatal() {
    let Some(rs) = both(&Case::main("badrange").env("GHA2DB_RECONCILE_RANGE", "bogus")) else {
        return;
    };
    assert_eq!(rs.code(), Some(2));
    assert_eq!(
        rs.error().as_deref(),
        Some("pq: invalid input syntax for type interval: \"bogus\"")
    );
    assert!(!rs.has_line_starting("reconcile_dbs: "));
    assert_eq!(rs.event_ids(), [T1.id, E1.id]);
}

#[test]
fn no_common_repositories_means_nothing_to_do() {
    let target = Db::new(&[201], &[], &[], &[21], &[]);
    let Some(rs) = both(&Case::main("noscope").db("tgt", target)) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert_eq!(
        rs.lines(),
        [
            header(
                "explicit (GHA2DB_RECONCILE_DBS)",
                "<dbs>_src",
                "90 days",
                "native, orphan",
                false
            ),
            NO_FILTER.to_string(),
            format!("{P}: scope 0 repo(s) (target 1, source 4)"),
            "reconcile_dbs: <dbs>_tgt: 1 source(s), copied 0 event(s), inserted 0 row(s), filtered out 0 event(s), skipped 0 orphan event(s), taken over 0 commit(s)".to_string(),
            "Time: <duration>".to_string(),
        ]
    );
    assert!(rs.event_ids().is_empty());
}

#[test]
fn empty_source_has_no_differing_buckets() {
    let Some(rs) =
        both(&Case::main("emptysrc").db("src", Db::new(&[101, 102], &[11], &[], &[], &[])))
    else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert!(rs.has_line(&format!("{P}: scope 2 repo(s) (target 3, source 2)")));
    assert!(rs.has_line(&format!("{P}: buckets: source 0, target 2, differing 0")));
    assert!(!rs.has_line_starting(&format!("{P}: events:")));
    assert!(rs.has_line(
        "reconcile_dbs: <dbs>_tgt: 1 source(s), copied 0 event(s), inserted 0 row(s), filtered out 0 event(s), skipped 0 orphan event(s), taken over 0 commit(s)"
    ));
}

// ---------------------------------------------------------------------------
// Fatal configuration errors
// ---------------------------------------------------------------------------

#[test]
fn explicit_source_equal_to_the_target_is_fatal() {
    let Some(rs) = both(&Case::main("selfsrc").env("GHA2DB_RECONCILE_DBS", "{db:src},{db:tgt}"))
    else {
        return;
    };
    assert_eq!(rs.code(), Some(2));
    assert_eq!(
        rs.error().as_deref(),
        Some("reconcile_dbs: source database '<dbs>_tgt' is the target database")
    );
    assert_eq!(rs.event_ids(), [T1.id, E1.id]);
}

#[test]
fn explicit_missing_source_is_fatal() {
    let Some(rs) = both(
        &Case::main("nosrc")
            .missing("ghost")
            .env("GHA2DB_RECONCILE_DBS", "{db:ghost}"),
    ) else {
        return;
    };
    assert_eq!(rs.code(), Some(2));
    assert_eq!(
        rs.error().as_deref(),
        Some("pq: database \"<dbs>_ghost\" does not exist")
    );
    assert!(rs.has_line_starting("reconcile_dbs: <dbs>_tgt: mode explicit"));
}

#[test]
fn missing_target_is_fatal() {
    let Some(rs) = both(
        &Case::new("notgt")
            .db("src", main_source())
            .empty_db("tgt")
            .missing("absent")
            .env("PG_DB", "{db:absent}")
            .env("GHA2DB_RECONCILE_DBS", "{db:src}"),
    ) else {
        return;
    };
    assert_eq!(rs.code(), Some(2));
    assert_eq!(
        rs.error().as_deref(),
        Some("pq: database \"<dbs>_absent\" does not exist")
    );
}

#[test]
fn context_dump_includes_the_reconcile_skip_knob() {
    let Some(rs) = both(
        &Case::main("ctxout")
            .env("GHA2DB_CTXOUT", "1")
            .env("GHA2DB_RECONCILESKIP", "1")
            .env("GHA2DB_RECONCILE_DRY_RUN", "1"),
    ) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    let dump = rs.outs[0]
        .stdout_str()
        .lines()
        .find(|l| l.contains(" SkipReconcile:"))
        .map(str::to_string)
        .expect("context dump");
    assert!(
        dump.contains(" SkipGetRepos:false SkipReconcile:true "),
        "{dump}"
    );
}

// ---------------------------------------------------------------------------
// projects.yaml driven modes
// ---------------------------------------------------------------------------

/// Shared mode: the target is the shared database of `alpha`, `beta`,
/// `beta2` (same database as `beta`), the disabled `gamma`, `ghost` (missing
/// database) and the self-referencing `selfref`; `other` shares elsewhere,
/// `nodb` has no database.
const SHARED_YAML: &str = r#"---
projects:
  alpha:
    name: Alpha
    psql_db: " {db:p1} "
    shared_db: "  {db:tgt}  "
    order: 2
  beta:
    name: Beta
    psql_db: {db:p2}
    shared_db: {db:tgt}
    order: 1
  beta2:
    name: Beta Two
    psql_db: {db:p2}
    shared_db: {db:tgt}
    order: 1
  gamma:
    name: Gamma
    psql_db: {db:p3}
    shared_db: {db:tgt}
    disabled: true
    order: 0
  ghost:
    name: Ghost
    psql_db: {db:ghost}
    shared_db: {db:tgt}
    order: 3
  other:
    name: Other
    psql_db: {db:p3}
    shared_db: elsewhere
    order: 4
  selfref:
    name: Self
    psql_db: {db:tgt}
    shared_db: {db:tgt}
    order: 5
  nodb:
    name: No DB
    psql_db: ""
    shared_db: {db:tgt}
    order: 6
"#;

/// `p1`: the pushes and the orphans; `p2`: the issue and the pull request;
/// `p3` (disabled `gamma`): the artificial event (never reached).
fn shared_case(name: &'static str) -> Case {
    let p1 = Db::new(
        &[101, 102, 103],
        &[11, 12],
        &[],
        &[21, 22],
        &[E1, E2, E4, E5, O1, O2],
    );
    let p2 = Db::new(&[102, 104], &[11], &[5, 6], &[21, 22], &[E3, E6, E7]);
    let p3 = Db::new(&[101], &[11], &[], &[21], &[A1]);
    Case::new(name)
        .db("tgt", main_target())
        .db("p1", p1)
        .db("p2", p2)
        .db("p3", p3)
        .missing("ghost")
        .yaml(SHARED_YAML)
}

const P1: &str = "reconcile_dbs: <dbs>_tgt <- <dbs>_p1";
const P2: &str = "reconcile_dbs: <dbs>_tgt <- <dbs>_p2";

#[test]
fn shared_mode_pulls_from_every_project_database() {
    let Some(rs) = both(&shared_case("shared")) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert_eq!(
        rs.lines(),
        [
            header(
                "shared (projects with shared_db '<dbs>_tgt' in ./projects.yaml)",
                "<dbs>_p2, <dbs>_p1, <dbs>_ghost",
                "90 days",
                "native, orphan",
                false
            ),
            filter_line("selfref", "any org", "any repo", 0, false),
            format!("{P2}: scope 2 repo(s) (target 3, source 2)"),
            format!("{P2}: buckets: source 2, target 0, differing 2"),
            format!("{P2}: events: source-only 3 (native 3, orphan 0, artificial 0), target-only 0"),
            format!("{P2}: table gha_events: rows 3, inserted 3"),
            format!("{P2}: table gha_payloads: rows 3, inserted 3"),
            format!("{P2}: table gha_comments: rows 1, inserted 1"),
            format!("{P2}: table gha_issues: rows 1, inserted 1"),
            format!("{P2}: table gha_issues_labels: rows 1, inserted 1"),
            format!("{P2}: table gha_pull_requests: rows 1, inserted 1"),
            format!("{P2}: table gha_reviews: rows 1, inserted 1"),
            format!("{P2}: table gha_repos: rows 2, inserted 0"),
            format!("{P2}: table gha_orgs: rows 1, inserted 0"),
            format!("{P2}: table gha_labels: rows 1, inserted 1"),
            format!("{P2}: table gha_actors: rows 2, inserted 1"),
            format!("{P2}: copied 3 event(s), inserted 13 row(s), postprocess 3 event id(s)"),
            "targeted postprocess executed for 3 restored event id(s)".to_string(),
            format!("{P1}: scope 2 repo(s) (target 3, source 3)"),
            // Scope 101, 102: E1's day (count differs), O1's and O2's days; the
            // target's T1 and E3+E7 (copied from p2) days are not the source's.
            format!("{P1}: buckets: source 3, target 3, differing 3"),
            format!("{P1}: events: source-only 3 (native 1, orphan 2, artificial 0), target-only 0"),
            format!("{P1}: skipped 1 orphan event(s) whose commits are already present"),
            format!("{P1}: table gha_events: rows 2, inserted 2"),
            format!("{P1}: table gha_payloads: rows 2, inserted 2"),
            format!("{P1}: table gha_commits: rows 2, inserted 2"),
            format!("{P1}: table gha_commits_roles: rows 4, inserted 4"),
            format!("{P1}: table gha_repos: rows 2, inserted 0"),
            format!("{P1}: table gha_orgs: rows 1, inserted 0"),
            format!("{P1}: table gha_actors: rows 1, inserted 0"),
            format!("{P1}: copied 2 event(s), inserted 10 row(s), postprocess 2 event id(s)"),
            "targeted postprocess executed for 2 restored event id(s)".to_string(),
            "reconcile_dbs: <dbs>_tgt <- <dbs>_ghost: source database unavailable, skipping: pq: database \"<dbs>_ghost\" does not exist".to_string(),
            "reconcile_dbs: <dbs>_tgt: 2 source(s), copied 5 event(s), inserted 23 row(s), filtered out 0 event(s), skipped 1 orphan event(s), taken over 0 commit(s)".to_string(),
            "Time: <duration>".to_string(),
        ]
    );
    assert_eq!(
        rs.event_ids(),
        [O2.id, T1.id, E1.id, E2.id, E3.id, E6.id, E7.id]
    );
}

/// The shared database's own project (`selfref` here, `all` on the clusters)
/// decides what is pulled from the children: its org list and its
/// `GHA2DB_EXCLUDE_REPOS` are applied to every source, so the shared database
/// never receives events its own `gha2db` would not ingest (the children may
/// track more, fewer or different repositories than the shared project).
#[test]
fn shared_mode_applies_the_shared_projects_own_rules() {
    let yaml = leak(&SHARED_YAML.replace(
        "  selfref:\n    name: Self\n    psql_db: {db:tgt}\n    shared_db: {db:tgt}\n    order: 5\n",
        "  selfref:\n    name: Self\n    psql_db: {db:tgt}\n    shared_db: {db:tgt}\n    command_line: ['org1']\n    env:\n      GHA2DB_EXCLUDE_REPOS: org1/repo2\n    order: 5\n",
    ));
    assert!(
        yaml.contains("GHA2DB_EXCLUDE_REPOS"),
        "selfref block not found in SHARED_YAML"
    );
    let Some(rs) = both(&shared_case("sharedfilter").yaml(yaml)) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert!(rs.has_line(&filter_line("selfref", "1 org(s)", "any repo", 1, false)));
    // p2: E3 and E7 (org1/repo2 is excluded) and E6 (no organization) are all
    // dropped, so nothing is copied from it.
    assert!(rs.has_line(&format!(
        "{P2}: events: source-only 3 (native 3, orphan 0, artificial 0), target-only 0"
    )));
    assert!(rs.has_line(&format!(
        "{P2}: filtered out 3 event(s) outside project 'selfref' org/repo/actor rules (native 3, orphan 0, artificial 0)"
    )));
    assert!(!rs.has_line_starting(&format!("{P2}: copied ")));
    // p1: O2 (org1/repo2) is dropped before the commit check, O1 passes the
    // rules but its commit is already present, E2 is copied.
    assert!(rs.has_line(&format!(
        "{P1}: events: source-only 3 (native 1, orphan 2, artificial 0), target-only 0"
    )));
    assert!(rs.has_line(&format!(
        "{P1}: filtered out 1 event(s) outside project 'selfref' org/repo/actor rules (native 0, orphan 1, artificial 0)"
    )));
    assert!(rs.has_line(&format!(
        "{P1}: skipped 1 orphan event(s) whose commits are already present"
    )));
    assert!(rs.has_line(&format!(
        "{P1}: copied 1 event(s), inserted 6 row(s), postprocess 1 event id(s)"
    )));
    assert!(rs.has_line(
        "reconcile_dbs: <dbs>_tgt: 2 source(s), copied 1 event(s), inserted 6 row(s), filtered out 4 event(s), skipped 1 orphan event(s), taken over 0 commit(s)"
    ));
    assert_eq!(rs.event_ids(), [T1.id, E1.id, E2.id]);
}

/// `GHA2DB_PROJECT` naming a child project does not switch the rules: the
/// shared database is still filtered by its own project (`selfref`).
#[test]
fn shared_mode_with_a_child_project_name_still_uses_the_shared_projects_rules() {
    let yaml = leak(&SHARED_YAML.replace(
        "  selfref:\n    name: Self\n    psql_db: {db:tgt}\n    shared_db: {db:tgt}\n    order: 5\n",
        "  selfref:\n    name: Self\n    psql_db: {db:tgt}\n    shared_db: {db:tgt}\n    command_line: ['org1']\n    env:\n      GHA2DB_EXCLUDE_REPOS: org1/repo2\n    order: 5\n",
    ));
    let Some(rs) = both(
        &shared_case("sharedchild")
            .yaml(yaml)
            .env("GHA2DB_PROJECT", "alpha"),
    ) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert!(rs.has_line_starting(
        "reconcile_dbs: <dbs>_tgt: mode shared (projects with shared_db '<dbs>_tgt' in ./projects.yaml), 3 source(s): <dbs>_p2, <dbs>_p1, <dbs>_ghost"
    ));
    assert!(rs.has_line(&filter_line("selfref", "1 org(s)", "any repo", 1, false)));
    assert!(rs.has_line(&format!(
        "{P2}: filtered out 3 event(s) outside project 'selfref' org/repo/actor rules (native 3, orphan 0, artificial 0)"
    )));
    assert!(rs.has_line(&format!(
        "{P1}: filtered out 1 event(s) outside project 'selfref' org/repo/actor rules (native 0, orphan 1, artificial 0)"
    )));
    assert!(rs.has_line(
        "reconcile_dbs: <dbs>_tgt: 2 source(s), copied 1 event(s), inserted 6 row(s), filtered out 4 event(s), skipped 1 orphan event(s), taken over 0 commit(s)"
    ));
    assert_eq!(rs.event_ids(), [T1.id, E1.id, E2.id]);
}

#[test]
fn shared_mode_skips_the_listed_databases() {
    let Some(rs) = both(&shared_case("sharedskip").env(
        "GHA2DB_RECONCILE_SKIP_DBS",
        "{db:p1}, {db:ghost},nonexistent",
    )) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    let lines = rs.lines();
    assert_eq!(
        lines[0],
        "reconcile_dbs: <dbs>_tgt: skipped 2 source(s) using GHA2DB_RECONCILE_SKIP_DBS: <dbs>_p1, <dbs>_ghost"
    );
    assert_eq!(
        lines[1],
        header(
            "shared (projects with shared_db '<dbs>_tgt' in ./projects.yaml)",
            "<dbs>_p2",
            "90 days",
            "native, orphan",
            false
        )
    );
    assert!(!rs.has_line_starting(P1));
    assert!(rs.has_line(
        "reconcile_dbs: <dbs>_tgt: 1 source(s), copied 3 event(s), inserted 13 row(s), filtered out 0 event(s), skipped 0 orphan event(s), taken over 0 commit(s)"
    ));
}

#[test]
fn skipping_every_source_is_nothing_to_do() {
    let Some(rs) = both(
        &shared_case("sharedskipall")
            .env("GHA2DB_RECONCILE_SKIP_DBS", "{db:p1},{db:p2},{db:ghost}"),
    ) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert_eq!(
        rs.lines(),
        [
            "reconcile_dbs: <dbs>_tgt: skipped 3 source(s) using GHA2DB_RECONCILE_SKIP_DBS: <dbs>_p2, <dbs>_p1, <dbs>_ghost".to_string(),
            "reconcile_dbs: <dbs>_tgt: no source databases, nothing to reconcile".to_string(),
            "Time: <duration>".to_string(),
        ]
    );
    assert_eq!(rs.event_ids(), [T1.id, E1.id]);
}

#[test]
fn projects_override_enables_a_disabled_project() {
    let Some(rs) = both(
        &shared_case("override")
            .env("GHA2DB_PROJECTS_OVERRIDE", "+gamma,-beta,-beta2")
            .env("GHA2DB_RECONCILE_ARTIFICIAL", "1"),
    ) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    let lines = rs.lines();
    assert_eq!(
        lines[0],
        header(
            "shared (projects with shared_db '<dbs>_tgt' in ./projects.yaml)",
            "<dbs>_p3, <dbs>_p1, <dbs>_ghost",
            "90 days",
            "native, orphan, artificial",
            false
        )
    );
    let p3 = "reconcile_dbs: <dbs>_tgt <- <dbs>_p3";
    assert!(rs.has_line(&format!(
        "{p3}: events: source-only 1 (native 0, orphan 0, artificial 1), target-only 0"
    )));
    assert!(rs.has_line(&format!(
        "{p3}: copied 1 event(s), inserted 2 row(s), postprocess 1 event id(s)"
    )));
    assert!(rs.event_ids().contains(&A1.id));
}

#[test]
fn shared_mode_reads_the_yaml_from_the_data_directory() {
    let Some(rs) = both(&shared_case("datadir").datadir()) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert_eq!(
        rs.lines()[0],
        header(
            "shared (projects with shared_db '<dbs>_tgt' in <dir>/projects.yaml)",
            "<dbs>_p2, <dbs>_p1, <dbs>_ghost",
            "90 days",
            "native, orphan",
            false
        )
    );
    // The postprocess scripts are read from the data directory too.
    assert!(rs.has_line("targeted postprocess executed for 3 restored event id(s)"));
    assert!(rs.has_line(
        "reconcile_dbs: <dbs>_tgt: 2 source(s), copied 5 event(s), inserted 23 row(s), filtered out 0 event(s), skipped 1 orphan event(s), taken over 0 commit(s)"
    ));
}

#[test]
fn custom_projects_yaml_name() {
    let Some(rs) = both(&shared_case("yamlname").env("GHA2DB_PROJECTS_YAML", "projects.yaml"))
    else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert!(rs.has_line_starting(
        "reconcile_dbs: <dbs>_tgt: mode shared (projects with shared_db '<dbs>_tgt' in ./projects.yaml)"
    ));
}

#[test]
fn missing_projects_yaml_is_fatal() {
    let Some(rs) = both(&shared_case("noyaml").env("GHA2DB_PROJECTS_YAML", "missing.yaml")) else {
        return;
    };
    assert_eq!(rs.code(), Some(2));
    assert_eq!(
        rs.error().as_deref(),
        Some("open ./missing.yaml: no such file or directory")
    );
    assert_eq!(rs.event_ids(), [T1.id, E1.id]);
}

/// Project mode: `alpha` and `zeta` live in the target database (`alpha`
/// sharing into `src`, `zeta` into the missing `ghost`), `omega` is a
/// disabled project of the same database, `beta` has no shared database.
const PROJECT_YAML: &str = r#"---
projects:
  zeta:
    name: Zeta
    psql_db: {db:tgt}
    shared_db: {db:ghost}
    order: 2
  alpha:
    name: Alpha
    psql_db: {db:tgt}
    shared_db: " {db:src} "
    order: 1
  omega:
    name: Omega
    psql_db: {db:tgt}
    shared_db: {db:ghost}
    disabled: true
    order: 0
  beta:
    name: Beta
    psql_db: {db:beta}
    order: 3
  other:
    name: Other
    psql_db: {db:src}
    shared_db: elsewhere
    order: 4
"#;

fn project_case(name: &'static str) -> Case {
    Case::new(name)
        .db("tgt", main_target())
        .db("src", main_source())
        .db("beta", Db::new(&[101], &[11], &[], &[21], &[E1]))
        .missing("ghost")
        .yaml(PROJECT_YAML)
}

#[test]
fn project_mode_uses_the_given_project() {
    let Some(rs) = both(&project_case("project").env("GHA2DB_PROJECT", "alpha")) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert_eq!(
        rs.lines()[0],
        header(
            "project (project 'alpha' shared_db '<dbs>_src' in ./projects.yaml)",
            "<dbs>_src",
            "90 days",
            "native, orphan",
            false
        )
    );
    assert!(rs.has_line(
        "reconcile_dbs: <dbs>_tgt: 1 source(s), copied 5 event(s), inserted 23 row(s), filtered out 0 event(s), skipped 1 orphan event(s), taken over 0 commit(s)"
    ));
    assert_eq!(
        rs.event_ids(),
        [O2.id, T1.id, E1.id, E2.id, E3.id, E6.id, E7.id]
    );
}

#[test]
fn project_mode_finds_the_project_by_database() {
    // No GHA2DB_PROJECT: the lowest (order, name) enabled project of the
    // database - alpha (omega is disabled).
    let Some(rs) = both(&project_case("projectbydb")) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert!(rs.has_line_starting(
        "reconcile_dbs: <dbs>_tgt: mode project (project 'alpha' shared_db '<dbs>_src' in ./projects.yaml)"
    ));
}

#[test]
fn project_mode_with_a_missing_shared_database_is_not_fatal() {
    // Unlike the explicit mode, the yaml driven modes skip unavailable databases.
    let Some(rs) = both(&project_case("projectghost").env("GHA2DB_PROJECT", "zeta")) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert_eq!(
        rs.lines(),
        [
            header(
                "project (project 'zeta' shared_db '<dbs>_ghost' in ./projects.yaml)",
                "<dbs>_ghost",
                "90 days",
                "native, orphan",
                false
            ),
            filter_line("zeta", "any org", "any repo", 0, false),
            "reconcile_dbs: <dbs>_tgt <- <dbs>_ghost: source database unavailable, skipping: pq: database \"<dbs>_ghost\" does not exist".to_string(),
            "reconcile_dbs: <dbs>_tgt: 0 source(s), copied 0 event(s), inserted 0 row(s), filtered out 0 event(s), skipped 0 orphan event(s), taken over 0 commit(s)".to_string(),
            "Time: <duration>".to_string(),
        ]
    );
    assert_eq!(rs.event_ids(), [T1.id, E1.id]);
}

#[test]
fn project_mode_ignores_a_project_of_another_database() {
    // GHA2DB_PROJECT names a project living elsewhere (or disabled): the
    // database's own lowest project wins.
    let Some(rs) = both(&project_case("projectother").env("GHA2DB_PROJECT", "other")) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert!(rs.has_line_starting(
        "reconcile_dbs: <dbs>_tgt: mode project (project 'alpha' shared_db '<dbs>_src' in ./projects.yaml)"
    ));
    let Some(rs) = both(&project_case("projectdisabled").env("GHA2DB_PROJECT", "omega")) else {
        return;
    };
    assert!(rs.has_line_starting(
        "reconcile_dbs: <dbs>_tgt: mode project (project 'alpha' shared_db '<dbs>_src' in ./projects.yaml)"
    ));
}

#[test]
fn project_without_shared_database_has_nothing_to_reconcile() {
    let Some(rs) = both(&project_case("noshared").env("PG_DB", "{db:beta}")) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert_eq!(
        rs.lines(),
        [
            "reconcile_dbs: <dbs>_beta: project 'beta' has no shared database in ./projects.yaml, nothing to reconcile".to_string(),
            "Time: <duration>".to_string(),
        ]
    );
}

#[test]
fn database_without_a_project_has_nothing_to_reconcile() {
    let Some(rs) = both(
        &Case::new("noproject")
            .db("tgt", main_target())
            .db("src", main_source())
            .yaml("---\nprojects:\n  alpha:\n    name: Alpha\n    psql_db: {db:src}\n    shared_db: {db:tgt}\n    disabled: true\n"),
    ) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert_eq!(
        rs.lines(),
        [
            "reconcile_dbs: <dbs>_tgt: no enabled project uses this database in ./projects.yaml, nothing to reconcile".to_string(),
            "Time: <duration>".to_string(),
        ]
    );
    assert_eq!(rs.event_ids(), [T1.id, E1.id]);
}

// ---------------------------------------------------------------------------
// Project ingestion rules (bug #74): only what the target's gha2db would take
// ---------------------------------------------------------------------------

/// Project mode yaml of the main world: `alpha` (target) shares into `src`
/// with the given `command_line` (and `env`).
fn filter_yaml(command_line: &str, env: &str) -> &'static str {
    leak(&format!(
        "---\nprojects:\n  alpha:\n    name: Alpha\n    psql_db: {{db:tgt}}\n    shared_db: {{db:src}}\n    command_line: {command_line}\n{env}    order: 1\n"
    ))
}

fn filter_case(name: &'static str, command_line: &str, env: &str) -> Case {
    Case::new(name)
        .db("tgt", main_target())
        .db("src", main_source())
        .yaml(filter_yaml(command_line, env))
        .env("GHA2DB_PROJECT", "alpha")
}

/// Source-only events of the main world: E2 (org1/repo1, bob), E3 and E7
/// (org1/repo2, alice), E6 (solo/repo4, bob), O1 (org1/repo1, alice, its
/// commit is already present), O2 (org1/repo2, bob).
#[test]
fn events_outside_the_project_org_list_are_not_copied() {
    // The repository that moved to another org (no org here) is not pulled.
    let Some(rs) = both(&filter_case("filterorg", "[' org1 ']", "")) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert_eq!(
        rs.lines(),
        [
            header(
                "project (project 'alpha' shared_db '<dbs>_src' in ./projects.yaml)",
                "<dbs>_src",
                "90 days",
                "native, orphan",
                false
            ),
            filter_line("alpha", "1 org(s)", "any repo", 0, false),
            format!("{P}: scope 3 repo(s) (target 3, source 4)"),
            format!("{P}: buckets: source 5, target 2, differing 5"),
            format!("{P}: events: source-only 6 (native 4, orphan 2, artificial 0), target-only 0"),
            format!("{P}: filtered out 1 event(s) outside project 'alpha' org/repo/actor rules (native 1, orphan 0, artificial 0)"),
            format!("{P}: skipped 1 orphan event(s) whose commits are already present"),
            format!("{P}: table gha_events: rows 4, inserted 4"),
            format!("{P}: table gha_payloads: rows 4, inserted 4"),
            format!("{P}: table gha_commits: rows 2, inserted 2"),
            format!("{P}: table gha_commits_roles: rows 4, inserted 4"),
            format!("{P}: table gha_comments: rows 1, inserted 1"),
            format!("{P}: table gha_issues: rows 1, inserted 1"),
            format!("{P}: table gha_issues_labels: rows 1, inserted 1"),
            format!("{P}: table gha_pull_requests: rows 1, inserted 1"),
            format!("{P}: table gha_reviews: rows 1, inserted 1"),
            format!("{P}: table gha_repos: rows 2, inserted 0"),
            format!("{P}: table gha_orgs: rows 1, inserted 0"),
            format!("{P}: table gha_labels: rows 1, inserted 1"),
            format!("{P}: table gha_actors: rows 2, inserted 1"),
            format!("{P}: copied 4 event(s), inserted 21 row(s), postprocess 4 event id(s)"),
            "targeted postprocess executed for 4 restored event id(s)".to_string(),
            "reconcile_dbs: <dbs>_tgt: 1 source(s), copied 4 event(s), inserted 21 row(s), filtered out 1 event(s), skipped 1 orphan event(s), taken over 0 commit(s)".to_string(),
            "Time: <duration>".to_string(),
        ]
    );
    assert_eq!(rs.event_ids(), [O2.id, T1.id, E1.id, E2.id, E3.id, E7.id]);
}

#[test]
fn org_and_repo_lists_and_the_exclude_list_are_applied() {
    // Org and repo lists: only org1/repo1 events (E2; O1 is skipped).
    let Some(rs) = both(&filter_case("filterrepo", "['org1', 'repo1']", "")) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert!(rs.has_line(&filter_line("alpha", "1 org(s)", "1 repo(s)", 0, false)));
    assert!(rs.has_line(&format!(
        "{P}: filtered out 4 event(s) outside project 'alpha' org/repo/actor rules (native 3, orphan 1, artificial 0)"
    )));
    assert!(rs.has_line(
        "reconcile_dbs: <dbs>_tgt: 1 source(s), copied 1 event(s), inserted 6 row(s), filtered out 4 event(s), skipped 1 orphan event(s), taken over 0 commit(s)"
    ));
    assert_eq!(rs.event_ids(), [T1.id, E1.id, E2.id]);

    // The project's env (GHA2DB_EXCLUDE_REPOS) is applied like gha2db_sync does.
    let Some(rs) = both(&filter_case(
        "filterexclude",
        "['org1']",
        "    env:\n      GHA2DB_EXCLUDE_REPOS: org1/repo2\n",
    )) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert!(rs.has_line(&filter_line("alpha", "1 org(s)", "any repo", 1, false)));
    assert!(rs.has_line(&format!(
        "{P}: filtered out 4 event(s) outside project 'alpha' org/repo/actor rules (native 3, orphan 1, artificial 0)"
    )));
    assert_eq!(rs.event_ids(), [T1.id, E1.id, E2.id]);

    // ... unless ENV_SET says the environment was prepared already (by `devstats`).
    let Some(rs) = both(
        &filter_case(
            "filterenvset",
            "['org1']",
            "    env:\n      GHA2DB_EXCLUDE_REPOS: org1/repo2\n",
        )
        .env("ENV_SET", "1"),
    ) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert!(rs.has_line(&filter_line("alpha", "1 org(s)", "any repo", 0, false)));
    assert!(rs.has_line(&format!(
        "{P}: filtered out 1 event(s) outside project 'alpha' org/repo/actor rules (native 1, orphan 0, artificial 0)"
    )));
    assert_eq!(rs.event_ids(), [O2.id, T1.id, E1.id, E2.id, E3.id, E7.id]);
}

#[test]
fn regexp_and_actor_rules_are_applied() {
    // `regexp:` on the full repository name.
    let Some(rs) = both(&filter_case(
        "filterregexp",
        r"['regexp:^org1\/repo2$']",
        "",
    )) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert!(rs.has_line(&filter_line(
        "alpha",
        r"org regexp '^org1\/repo2$'",
        "any repo",
        0,
        false
    )));
    assert!(rs.has_line(&format!(
        "{P}: filtered out 3 event(s) outside project 'alpha' org/repo/actor rules (native 2, orphan 1, artificial 0)"
    )));
    // O1 (org1/repo1) is filtered out before the orphan check.
    assert!(!rs.has_line_starting(&format!("{P}: skipped ")));
    assert_eq!(rs.event_ids(), [O2.id, T1.id, E1.id, E3.id, E7.id]);

    // Actor rules (GHA2DB_ACTORS_FILTER/FORBID): bob's events are not taken.
    let Some(rs) = both(
        &filter_case("filteractors", "['org1']", "")
            .env("GHA2DB_ACTORS_FILTER", "1")
            .env("GHA2DB_ACTORS_FORBID", "^bob$"),
    ) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert!(rs.has_line(&filter_line("alpha", "1 org(s)", "any repo", 0, true)));
    assert!(rs.has_line(&format!(
        "{P}: filtered out 3 event(s) outside project 'alpha' org/repo/actor rules (native 2, orphan 1, artificial 0)"
    )));
    assert!(rs.has_line(&format!(
        "{P}: skipped 1 orphan event(s) whose commits are already present"
    )));
    assert_eq!(rs.event_ids(), [T1.id, E1.id, E3.id, E7.id]);
    assert_eq!(
        rs.query("select login from gha_actors order by id"),
        ["alice"]
    );
}

#[test]
fn a_second_run_after_filtering_copies_nothing_more() {
    // The filtered events keep their buckets differing; nothing is copied twice.
    let Some(rs) = both(&filter_case("filterrerun", "['org1']", "").runs(2)) else {
        return;
    };
    assert_eq!(rs.outs[1].code, Some(0));
    assert!(rs.lines_of(1).contains(&format!(
        "{P}: events: source-only 2 (native 1, orphan 1, artificial 0), target-only 0"
    )));
    assert!(rs.lines_of(1).contains(&format!(
        "{P}: filtered out 1 event(s) outside project 'alpha' org/repo/actor rules (native 1, orphan 0, artificial 0)"
    )));
    assert!(rs.lines_of(1).contains(
        &"reconcile_dbs: <dbs>_tgt: 1 source(s), copied 0 event(s), inserted 0 row(s), filtered out 1 event(s), skipped 1 orphan event(s), taken over 0 commit(s)".to_string()
    ));
}

/// `GHA2DB_RECONCILE_HIST=1`: the project's historical rules
/// (`hist_command_line`, the biggest scope it ever had) decide instead of the
/// daily `command_line`; a project without them keeps the daily rules.
#[test]
fn historical_rules_pull_the_repositories_the_project_used_to_track() {
    // solo/repo4 (E6) was in the project's scope once: the folded double-quoted
    // `hist_command_line` (the way long lists are wrapped in projects.yaml) takes it.
    let Some(rs) = both(
        &filter_case(
            "filterhist",
            "['org1']",
            "    hist_command_line: [\"org1,\\\n       solo\"]\n",
        )
        .env("GHA2DB_RECONCILE_HIST", "1"),
    ) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert!(rs.has_line(
        "reconcile_dbs: <dbs>_tgt: filter: project 'alpha' (historical rules): 2 org(s), any repo, 0 excluded repo(s), exact false, actors filter false"
    ));
    assert!(!rs.has_line_starting(&format!("{P}: filtered out ")));
    assert!(
        rs.has_line(
            "reconcile_dbs: <dbs>_tgt: 1 source(s), copied 5 event(s), inserted 23 row(s), filtered out 0 event(s), skipped 1 orphan event(s), taken over 0 commit(s)"
        ),
        "{:#?}",
        rs.lines()
    );
    assert_eq!(
        rs.event_ids(),
        [O2.id, T1.id, E1.id, E2.id, E3.id, E6.id, E7.id]
    );

    // The daily run of the same project does not take it (hist rules are opt-in) ...
    let Some(rs) = both(&filter_case(
        "filterhistoff",
        "['org1']",
        "    hist_command_line: ['org1,solo']\n",
    )) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert!(rs.has_line(&filter_line("alpha", "1 org(s)", "any repo", 0, false)));
    assert_eq!(rs.event_ids(), [O2.id, T1.id, E1.id, E2.id, E3.id, E7.id]);

    // ... and a project without `hist_command_line` uses its `command_line` (and says so).
    let Some(rs) =
        both(&filter_case("filterhistnone", "['org1']", "").env("GHA2DB_RECONCILE_HIST", "1"))
    else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert!(rs.has_line(
        "reconcile_dbs: <dbs>_tgt: filter: project 'alpha' (historical rules: none, using command_line): 1 org(s), any repo, 0 excluded repo(s), exact false, actors filter false"
    ));
    assert!(rs.has_line(&format!(
        "{P}: filtered out 1 event(s) outside project 'alpha' org/repo/actor rules (native 1, orphan 0, artificial 0)"
    )));
    assert_eq!(rs.event_ids(), [O2.id, T1.id, E1.id, E2.id, E3.id, E7.id]);

    // Historical org and repo lists (two element form) and a `regexp:` on the full name.
    let Some(rs) = both(
        &filter_case(
            "filterhistrepo",
            "['org1', 'repo1']",
            "    hist_command_line:\n      - 'org1,solo'\n      - \"repo1,\\\n         repo4\"\n",
        )
        .env("GHA2DB_RECONCILE_HIST", "1"),
    ) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert!(rs.has_line(
        "reconcile_dbs: <dbs>_tgt: filter: project 'alpha' (historical rules): 2 org(s), 2 repo(s), 0 excluded repo(s), exact false, actors filter false"
    ));
    assert!(rs.has_line(&format!(
        "{P}: filtered out 3 event(s) outside project 'alpha' org/repo/actor rules (native 2, orphan 1, artificial 0)"
    )));
    assert_eq!(rs.event_ids(), [T1.id, E1.id, E2.id, E6.id]);
    let Some(rs) = both(
        &filter_case(
            "filterhistre",
            r"['regexp:^org1\/repo2$']",
            "    hist_command_line:\n      - \"regexp:(?:^org1/repo2$)|\\\n         ^(?:solo/repo4)$\"\n",
        )
        .env("GHA2DB_RECONCILE_HIST", "1"),
    ) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert!(rs.has_line(
        "reconcile_dbs: <dbs>_tgt: filter: project 'alpha' (historical rules): org regexp '(?:^org1/repo2$)|^(?:solo/repo4)$', any repo, 0 excluded repo(s), exact false, actors filter false"
    ));
    assert!(rs.has_line(&format!(
        "{P}: filtered out 2 event(s) outside project 'alpha' org/repo/actor rules (native 1, orphan 1, artificial 0)"
    )));
    assert_eq!(rs.event_ids(), [O2.id, T1.id, E1.id, E3.id, E6.id, E7.id]);
}

/// Explicit sources do not switch the rules off: when `projects.yaml` is
/// present, the target's project filters what is pulled (dry run here, so the
/// target stays untouched).
#[test]
fn explicit_mode_applies_the_yaml_rules_when_present() {
    let Some(rs) = both(
        &filter_case("explicitfilter", "['org1']", "")
            .env("GHA2DB_RECONCILE_DBS", "{db:src}")
            .env("GHA2DB_RECONCILE_DRY_RUN", "1"),
    ) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert_eq!(
        rs.lines()[0],
        header(
            "explicit (GHA2DB_RECONCILE_DBS)",
            "<dbs>_src",
            "90 days",
            "native, orphan",
            true
        )
    );
    assert_eq!(
        rs.lines()[1],
        filter_line("alpha", "1 org(s)", "any repo", 0, false)
    );
    assert!(rs.has_line(&format!(
        "{P}: filtered out 1 event(s) outside project 'alpha' org/repo/actor rules (native 1, orphan 0, artificial 0)"
    )));
    assert!(rs.has_line(&format!(
        "{P}: skipped 1 orphan event(s) whose commits are already present"
    )));
    assert!(rs.has_line(
        "reconcile_dbs: <dbs>_tgt: 1 source(s), would copy 4 event(s), inserted 0 row(s), filtered out 1 event(s), skipped 1 orphan event(s), taken over 0 commit(s)"
    ));
    assert_eq!(rs.event_ids(), [T1.id, E1.id]);
}

/// A `projects.yaml` where no enabled project owns the target database means
/// no rules: everything the source has is pulled (like without the file).
#[test]
fn explicit_mode_without_an_owning_project_filters_nothing() {
    let yaml = leak(
        "---\nprojects:\n  alpha:\n    name: Alpha\n    psql_db: {db:src}\n    shared_db: {db:tgt}\n    command_line: ['org1']\n    order: 1\n  omega:\n    name: Omega\n    psql_db: {db:tgt}\n    command_line: ['org1']\n    disabled: true\n    order: 2\n",
    );
    let Some(rs) = both(
        &Case::new("explicitnoowner")
            .db("tgt", main_target())
            .db("src", main_source())
            .yaml(yaml)
            .env("GHA2DB_RECONCILE_DBS", "{db:src}"),
    ) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert_eq!(
        rs.lines()[1],
        "reconcile_dbs: <dbs>_tgt: filter: none (no enabled project uses this database in ./projects.yaml)"
    );
    assert!(!rs.has_line_starting(&format!("{P}: filtered out ")));
    assert!(rs.has_line(
        "reconcile_dbs: <dbs>_tgt: 1 source(s), copied 5 event(s), inserted 23 row(s), filtered out 0 event(s), skipped 1 orphan event(s), taken over 0 commit(s)"
    ));
    assert_eq!(
        rs.event_ids(),
        [O2.id, T1.id, E1.id, E2.id, E3.id, E6.id, E7.id]
    );
}

#[test]
fn explicit_sources_win_over_the_yaml() {
    // GHA2DB_RECONCILE_DBS set: projects.yaml is not even read (missing here).
    let Some(rs) = both(
        &Case::main("explicitwins")
            .env("GHA2DB_PROJECT", "alpha")
            .env("GHA2DB_PROJECTS_YAML", "missing.yaml")
            .no_env("GHA2DB_RECONCILE_DBS")
            .env("GHA2DB_RECONCILE_DBS", "{db:src}"),
    ) else {
        return;
    };
    assert_eq!(rs.code(), Some(0));
    assert!(rs.has_line_starting("reconcile_dbs: <dbs>_tgt: mode explicit (GHA2DB_RECONCILE_DBS)"));
    assert!(rs.has_line("reconcile_dbs: <dbs>_tgt: filter: none (no ./missing.yaml)"));
}
